### ISSUE TITLE
File vs clipboard, full score vs selection: Specify MNX-Common for usage as a clipboard-format

### ISSUE THREAD

**Issue by CBoensel** [w3c/mnx#100]
MNX-Common is designed as an interchange format for music notation data. Right now, it covers data exchange via **files**. But what about data exchange via **clipboard**? 

### Initial Thoughts
When working with different apps at once, most sorts of media data selections (plain text, rich text, graphics, ...) can be exchanged between apps using the clipboard (**copy, cut, paste**). This is still not true for music notation data though. Therefore, **my first suggestion is to define how selections are encoded within MNX-Common, when one is not dealing with a full score.** 

The main **types/levels of musical selections** within a score I see are: 

- note-wise
- voice-wise
- bar-wise
- staff-wise
- score-wise

... + different combinations of the five. 

IMO, one ot the main challenges in specifying that area is to consider the varying contexts of the source and target. Music notation selections are sometimes sequences of musical material that can be pasted into a very different context from the one they came from. 

### Getting It Done
Of course, this would require active vendor interest and support. It becomes only useful, if at least a couple of software companies implement it in their editors. 

As its implementation is a very complex task that would require a lot of coding time, **my second suggestion is to define a subset of the most useful and most simple use cases**. Maybe we would find a couple of software companies taking the effort to start with that most viable subset of use cases at least. Any progress in this area would be a huge improvement... 

### Group Action
I discussed this in brief with @joeberkovitz already. What are your thoughts/ideas? Do you think any group effort in this area is beyond realistic or do we have options open?

**Comment by clnoel** [comment]
I think this would be awesome... but would it be V1? (And if it's not, we should put it aside for now!)

If it is V1, I think we should restrict it to single elements. That is, a measure, a sequence, a tuplet, a direction, an event, etc. Then you can just ship the whole element onto the clipboard and pull it down when pasting. I think I'd allow multiple measures. But not measures from different parts. They have to be from the same part. At least, for V1.

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.

I will note, though: since we moved to a JSON format, I think this particular use case is much more convenient. We've deliberately designed the various object types within MNX to be composable. So you could, for example, use just [the note object](https://w3c.github.io/mnx/docs/mnx-reference/objects/note/) (outside the context of a full document) as something to be copied to the clipboard.
