### ISSUE TITLE
Span-type directions need attributes to adjust their endpoints

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#12]
We need a mechanism for slurs and lines to not only specify their right ends in metrical terms, but to adjust both left and right ends positionally (since these notations commonly have both vertical and horizontal displacements at both ends, relative to the registration points on the notations that they connect).

**Comment by siennamw** [comment]
Because these adjustments do not have semantic meanings, this seems like a font and styling (CSS) issue.

**Comment by joeberkovitz** [comment]
This has been fixed by #82.
