### ISSUE TITLE
Allow measure location syntax to include indices

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#125]
The [measure location syntax ](https://w3c.github.io/mnx/specification/#measure-locations ) was created before the introduction of [measure indices](https://w3c.github.io/mnx/specification/#element-attrdef-measure-index). It would make sense to permit measure indices to be used in this context as well as (or instead of) element IDs.

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
