### ISSUE TITLE
The <beamed> "value" attribute should be renamed "duration"

### ISSUE THREAD

**Issue by notator** [w3c/mnx#130]
`<beamed>`'s `value` attribute should actually be called `duration` since it describes a duration, not a [**_note value_**](https://w3c.github.io/mnx/specification/#note-value) (like `<event>`'s `value` attribute).

The [definition of `<beamed> value`'s  _type_](https://w3c.github.io/mnx/specification/#the-beamed-element) also needs to be clarified in the spec.
It should either be a [**_note value quantity_**](https://w3c.github.io/mnx/specification/#note-value-multiple) (like a time-signature) or a [**_rational number_**](https://w3c.github.io/mnx/specification/#rational-number).

**Comment by joeberkovitz** [comment]
This change makes sense to me, unless there are objections I think we should create a PR and make this change.

**Comment by adrianholovaty** [comment]
Marking this as closed, as this refers to an older way of encoding beams (when they were collections of events). Now that beams are "outside" the sequence, this is fortunately no longer an issue.
