### ISSUE TITLE
Should "note value quantity" always have a numerator?

### ISSUE THREAD

**Issue by notator** [w3c/mnx#131]
A [**_note value quantity_**](https://w3c.github.io/mnx/specification/#note-value-quantity) is used to describe durations or time signatures. I think it should therefore always have a numerator.

In that case, the definition for parsing one should be changed, and the example of a single eighth-note **_note value quantitiy_** should be changed from "/8" to "1/8".

**Comment by adrianholovaty** [comment]
This is now indeed the case: https://w3c.github.io/mnx/docs/mnx-reference/objects/note-value-quantity/
