### ISSUE TITLE
Replace "performance" by "playback" in §6.1.3

### ISSUE THREAD

**Issue by notator** [w3c/mnx#134]
I have always been confused by the spec's use of the word "performance" (in §6.1.3).
After writing the [demo app](http://james-ingram.de/altMNX/cursors/demos/verticalLineCursorDemo/verticalLineCursorDemo.html) mentioned in #132, I think it would be helpful to differentiate more clearly between
- synchronizing live performances with a cursor travelling through the score,
- synchronizing the playback of external files (mp3s etc.) with a cursor travelling through the score.
- synchronizing the playback of information contained inside MNX files with a cursor travelling through the score.

"synchronizing" means something different (requires a different algorithm) in each of these three cases.
So:
1. The word "performance" should be reserved in the spec for live performance by human performers.
2. in $6.1.3 Performance content and all its subsections: the word "performance" should be replaced by the word "playback". So, for example, `<performance-event>` should be refactored to `<playback-event>`.

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
