### ISSUE TITLE
Piano music

### ISSUE THREAD

**Issue by Hodgkin2018** [w3c/mnx#140]
In piano music, a crescendo hairpin may be written between the two staves. The performer or transcriber needs to work out if this applies just to one hand, or both hands. In the MusicXML there would probably only be one crescendo attached to one staff. Is this something that MNX could improve upon?

**Comment by joeberkovitz** [comment]
The common-staff case is already dealt with by allowing directions to be placed in either the `<sequence>` element (the direction belongs to a specific voice) or the `<measure>` element (the directions belong to the measure as a whole). Please see https://w3c.github.io/mnx/specification/#the-directions-element

Where staves are used for multiple instruments, as in @shoogle's example, I'd argue that the underlying question is not cross-part sharing of directions, but the ability to combine multiple instruments in a single part. This will be allowed by MNX (as it already is in MusicXML) and is tracked by #104 already.
