### ISSUE TITLE
Encode semantic line breaks in lyrics

### ISSUE THREAD

**Issue by Hodgkin2018** [w3c/mnx#141]
To have a means to say, "this is the end of a line of lyrics". The advantage would be that transcription software could automatically break braille lines as lyric lines, instead of arbitrarily at bars. The advantage to sighted users is that it would make it much easier to quickly extract the words from a score and make a words-only copy?

**Comment by shoogle** [comment]
This was one of the many semantic lyric features mentioned in #139 (see "Semantic Information" section of [this comment](https://github.com/w3c/mnx/issues/139#issuecomment-406710337)):

> Where line breaks should occur when lyrics are written in libretto form

I agree this would be very useful.

**Comment by joeberkovitz** [comment]
Just a reminder to people - please give your issues informative titles. A single word is usually not enough to figure out what an issue means.

**Comment by adrianholovaty** [comment]
I've been working on this (encoding lyric line breaks) for Soundslice recently, and here are some things I've learned:

* The line break should be stored at least at the level of individual note — *not* at the level of a bar. Sometimes lyrics line breaks need to be in the middle of a bar.
* In some cases with multiple verses, the line break needs to go in a *different* place depending on the verse. Therefore it's most flexible to store the line break on a given lyric/verse as opposed to on an individual note.

**Comment by mdgood** [comment]
This is already supported in MusicXML with the `<end-line>` and `<end-paragraph>` elements. They are optional children of the `<lyric>` element, so they are stored at the per-lyric level as @adrianholovaty has suggested above. I would expect this would be carried over to MNX. Is there something that MNX could do differently than MusicXML to make this work better?

**Comment by shoogle** [comment]
`<end-line>` and `<end-paragraph>` are certainly a good starting point. I've been told that this is important for Braille music; I think because "system breaks" in Braille music traditionally match line breaks in the lyrics (as written out in verse/libretto form) rather than the system breaks in the CWMN score.

Perhaps an improvement would be to put these markers at the *beginning* of each paragraph and line rather than at the end. This would enable information to be stored about what the following paragraph represents, such as:

```xml
<begin-paragraph type="verse">        # first time words
<begin-paragraph type="simultaneous"> # sung at the same time as the first time words
<begin-paragraph type="alternative">  # optionally sung instead of the first time words
<begin-paragraph type="translation">  # optionally sung instead of the first time words
<begin-paragraph type="verse">        # second time words (sung on a repeat)
...
```

**Comment by adrianholovaty** [comment]
Closing this in favor of #357, which is a more up-to-date discussion.
