### ISSUE TITLE
Issues and considerations about processing MNX and working with MNX

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnx#143]
How will it be to work with MNX? To investigate this I made a program to convert MNX to MIDI. This gave a lot of considerations. I thought I mailed this to the group, but unfortunately it just entered item #104. Hope I can clean it up this way - to make this new issue with this collection of thoughts.
These considerations  might become issues if further discussion is needed. 

The MNX to MIDI program is of cause very limited in functionality and only a few example files exist, 
But my experience is that so far MNX works good.  

In the next comment I will bring my comment from 2018-09-02 and then a new comment.

**Comment by mogenslundholm** [comment]
(Comment from 2018-09-02)
I did a first step in making a program to process MNX-files - a simple program to convert the test file "FaurReveSample-common.xml" to Midi. It would be nice to have a very big example file to test the performance, but so far it seems to me that the program has high performance, due to the simplicity of the program. MNX is easy to process - so far.

Much depends on the specification of Multiple Instruments(#104), Grace Notes, Lyrics and Structural Elements. Hope to hear about how Dorico has solved it.

Working with this "MNX to MIDI"-converter raises some questions. Bring these here to promote discussion and record ideas. Importing the produced MIDI-file into "Notation Composer" looks good - except for the wrong accidentals of cause (Due to Midi-conversion).

1. Question: In an event: Can more than one instances of a pitch occur? Are pitches in an event different? Hope so, because then the notes can be a "set of notes". This gives an effective implementation. A tune that has two of the same note is the intro that Jimi Hendrix played in "Hey Joe", but they should go to two sequences anyway.

2. Key Fifths: "MusicXml" has two ways to specify the key: Either the "number of fifths" or "which fifths". Two ways to do a thing more than doubles the code and testing. The two ways are never equally used, so that the one solution is often poorly tested. With only one way to do it, this solution is tested all the time. Since the first way (Specifying number of fifths) is insufficient, I think that only the last solution (specifying each fifth) will do.

3. Tuplet: The test-file, "FaurReveSample-common.xml", that I have, uses "normal" and "actual" instead of "inner" and "outer". By the way - wasn't it better to have a ratio instead, i.e. "3/2"? (But "inner" and "outer" are intuitive, while I would not be sure if I should multiply with or divide by the ratio).

4. Duration measure="yes"? Wasn't it better to just specify the actual duration?

5. Dottet notes: Why use "d" - why not "." - more intuitive.

6. The duration - shouldn't it rather be "1/4" instead of "/4"?

7. Noting the note pitch G1. One or two octaves more? I.e. should G1 be noted G3 instead? No - not needed.

8. Could some requirements be more tight? E.g. Format = Unicode. (instead of either Ansi or "UTF8 little endian" or "UTF8 big endian" or ... )

9. In a sequence: why value? Everything is values. Why not "time" or "duration". (E.g. &lt;event value="/4"&gt;)

10. Event ID's in the first test file (ApresUnReve-generic.xml) are almost half of the file. Is it neccesary? Or is the intension that only the needed ID's should be present?

11. Identifying the changes in the manual. How to view changes (I am a Github novice).

12. (Off topic) Single/Begin/End: In XML the symbols may appear as "single", "begin" or "end" definitions e.g. Single definition: "&lt;note pitch="G4"/&gt;", or Begin definition: "&lt;note pitch="G4"&gt;" and End definition "&lt;/note&gt;". Are we to decide how to do it or does XML require that the single definition is equivalent to "&lt;note pitch="G4"&gt;&lt;/note&gt; ?

**Comment by mogenslundholm** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
	<META HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=windows-1252">
	<META NAME="GENERATOR" CONTENT="OpenOffice 4.1.2  (Win32)">
	<META NAME="CREATED" CONTENT="20090416;11320264">
	<META NAME="CHANGEDBY" CONTENT="Mogens Lundholm">
	<META NAME="CHANGED" CONTENT="20180919;18053725">
	<META NAME="Info 1" CONTENT="">
	<META NAME="Info 2" CONTENT="">
	<META NAME="Info 3" CONTENT="">
	<META NAME="Info 4" CONTENT="">
	<META NAME="CHANGEDBY" CONTENT="Mogens Lundholm">
</HEAD>
<BODY LANG="de-DE" DIR="LTR">
<P LANG="zxx" STYLE="margin-bottom: 0.5cm">More considerations
appeared when I continued to make a MNX to MIDI converter.<BR><BR>Symbols
appearing more than one place:<BR><BR>&lt;title&gt;: The Draft
Specification says: Context &quot;anywhere&quot;. Is it the only
symbol with no context at all? Thinking of the problems i MusixXML
and MIDI, I think a good idea is to have some well defined place to
have the title. Why can't the file name be the title? Because
non-ASCII letters just don't work properly in file names. (The worst
unsolvable problem i computerhistory: non-american letters). My
proposal for title: Context: &quot;identification, head&quot;. If
another definition is needed for classical music as Werktitel - Work
title, then such a thing coud be added without having it anywhere.&nbsp;&nbsp;&nbsp;
&nbsp;<BR><BR>&lt;measure&gt; The global section has also &lt;measure&gt;
but does it make sense? (#52, #55, #59, 89). A measure is a little
part of parts - shouldn't &quot;global&quot; be what is really
global? Let us say we have a tune with two parts and measure 7 is
equal. Should you put measure 7 in &lt;global&gt;? (what a merge
process you could have). <BR><BR>In the manual of 2018-08-28: In
sections 5.2.2.1 - 5.2.2.2 the note value &quot;*2&quot; described a
note of length 2, while 5/1 is 5 notes (As I read it). In myt head
&quot;*&quot; means multiply while &quot;1/8&quot; and &quot;2&quot; are
just numbers. To me this seems opposite: A star should mean multiple
notes while just a number should be the length. <BR><BR>Do we need a
place for discussions? An issue called &quot;issues&quot; for more
general discussion before placing some problem in a specific
issue?<BR><BR>What to do if the sequences are not equal length? (Hot
Cross buns) I thought that another element for whitespace could be
needed. It should be like &lt;rest&gt;, but not be visible in the
score nor make any delay. The only function is to set the position in
a measure. It should just fill the measure and make the sequences of
equal length.<BR>Especially for upbeat it could be usefull.<BR>Can
&quot;metrical position&quot; do that? <BR><BR>What to do if the
sequences are not equal length? (Hot Cross buns) I thought that
another element for whitespace could be needed. It should be like
&lt;rest&gt;, but not be visible in the score nor make any delay. The
only function is to set the position in a measure. It should just
fill the measure and make the sequences of equal length. Especially
for upbeat it could be usefull.<BR>Or can &quot;metrical position&quot;
do that? <BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;event value=&quot;/8&quot;&gt;<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;space/&gt;<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&lt;/event&gt;<BR><BR><BR>About the example-files: I had to do some
modifications of the available test files. Available testfiles (That
I found) are: &quot;FaurReveSample-common&quot;, &quot;Hot cross
buns&quot; and &quot;MultiMetric&quot; (In issue #55, How are
multi-metric scores are represented in CWMNX). <BR><BR>Change in
FaurReveSample-common: &quot;actual&quot; and &quot;normal&quot;&nbsp;
---&gt; &quot;inner&quot; and &quot;outer&quot;<BR><BR>Change in Hot
cross buns:<BR>&lt;system&gt; ---&gt; &lt;global&gt;<BR>&lt;attributes&gt;
---&gt; &lt;directions&gt;<BR>Added ---&gt; &lt;mnx-common&gt;
<BR><BR>Change in MultiMetric:<BR>&lt;cwmnx&gt;&nbsp;&nbsp; ---&gt;&nbsp;
&lt;mnx-common&gt;<BR><BR><BR>About &lt;wedge&gt;: To me &quot;start-stop&quot;
and &quot;begin-end&quot; are pairs, but in FaurReveSample-common
&quot;start-end&quot; appears &lt;wedge end=&quot;5/8&quot;
start=&quot;1/8&quot; type=&quot;crescendo&quot;/&gt;. Should it
rather be one of these?<BR>But why start? It starts here - shouldn't
it rather be 'length=&quot;5/8&quot;' ?<BR><BR>In the draft &lt;cresc&gt;
is described, but &lt;wedge&gt; has crescendo as type attribute.(pt.
5.2.10.4, 5.2.10.5) &quot;The cresc element represents a crescendo or
increasing dynamic level over the course of a span, notated as text
followed by a dashed line.&quot;<BR><BR>About dynamics: <BR>PS: We
have 26 dynamics: &quot;p, pp, ppp, pppp, ppppp, pppppp,<BR>f, ff,
fff, ffff, fffff, ffffff, mp mf, sf, sfp, sfpp, fp, rf, rfz, sfz,
sffz, fz n pf sfzp&quot;<BR>Should it rather be &lt;dynamics
type=&quot;f&quot;/&gt; ?</P>
<P LANG="zxx"><BR><BR>
</P>
<P LANG="zxx" STYLE="margin-bottom: 0cm"><BR>
</P>
</BODY>
</HTML>

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
