### ISSUE TITLE
The current draft specification is not in this repository

### ISSUE THREAD

**Issue by notator** [w3c/mnx#150]
The current draft specification is currently stored at
[https://w3c.github.io/mnx/specification/](https://w3c.github.io/mnx/specification/).

That spec is not the same as the one defined in
[https://github.com/w3c/mnx/tree/master/specification](https://github.com/w3c/mnx/tree/master/specification).

So pull requests on the spec defined in this repository will have no effect on the intended file.

This urgently needs sorting out, if we are to be able to make meaningful pull requests.
Which of these two files is the current version?
If its the one in this repository, then the other one should be marked as obsolete. 

While marking the current draft as obsolete is not the issue _here_, I discovered the problem while trying to create a pull request that would do that (in the same way as [https://w3c.github.io/mnx/overview/](https://w3c.github.io/mnx/overview/) is marked obsolete).

The specs at [https://w3c.github.io/mnx/specification/](https://w3c.github.io/mnx/specification/) and [https://w3c.github.io/mnx/overview/](https://w3c.github.io/mnx/overview/)
contain a `class="annoying-warning"` that is used for this purpose, but the spec in
[https://github.com/w3c/mnx/tree/master/specification](https://github.com/w3c/mnx/tree/master/specification) does not!

**Comment by dspreadbury** [comment]
The pages shown on the github.io site are all from the gh-pages branch. The gh-pages branch is effectively the master branch for these repositories. If you want to make a pull request against the draft specification, you should do so against the gh-pages branch rather than the master branch.

**Comment by adrianholovaty** [comment]
I've just gotten the full rundown from Joe B., regarding the `gh-pages` setup. It's a bit of a complicated arrangement, but the upshot is that we should make commits to `master`, and those commits will automatically be updated onto the `gh-pages` branch. This was a surprise to me as well; I did some experimentation yesterday in making commits on the two branches to see what would actually happen in practice. :)

I'm in the process of getting my own GitHub account set up with that automated system, at which point I'll have a much firmer grasp on how it all fits together. Once that's clear, I'll write up some documentation to prevent confusion in the future.
