### ISSUE TITLE
An Alternative Draft Specification

### ISSUE THREAD

**Issue by notator** [w3c/mnx#154]
I would like everyone to know that I have been working privately on an Alternative Draft Specification (with the co-chair's knowledge) since 9th May.  I've come to the conclusion, that [the current Draft Spec (16th May 2019)](https://w3c.github.io/mnx/specification/) needs revising completely, but that the necessary revision cannot be done by resolving single issues atomically. 
(I don't want to put a date on the completion of this revision, but it is well under way, and will materialise at some point.)

For example, in §2.7 I want to replace
>**Separate semantic concerns from presentation/interpretation concerns.**
Within its semantic encoding for MNX-Common, this specification strives to keep semantic descriptions from answering to the multitude of tiny features that control presentation and performance interpretation. These are segregated in the parallel domains of style properties and interpretation content.

by
>**Spatial and temporal information are kept strictly separate**
Conceptually, MNX files are parsed using different parsers for spatial and temporal information.
CSS-like style properties therefore affect either display (e.g. color) or audio characteristics (e.g. frequency or duration). See § 3.2.4.

This change not only leads to an interesting re-definition of the `<note>` element, but it also has other consequences. Its simply not possible to make the above change  'atomic'. Accepting it as a Pull Request on the current spec would immediately invalidate the rest of the spec.

This issue is related to several open, unresolved issues (e.g. #129, #142, #153) that assume the current Draft Spec as their point of departure. The problems they raise should be solved (in ways that could not have been foreseen when they were raised) by my new Draft Spec when it is ready.

#4 and #152 were closed on 15th May, but I think the ideas which began to develop [here on 8th April](https://github.com/w3c/mnx/issues/138#issuecomment-480789811), and continued [here in #4](https://github.com/w3c/mnx/issues/4#issuecomment-486733536) are too interesting to leave uninvestigated. Those ideas also connect interestingly to other work I've been doing over the years, so this project is worth doing for me personally, quite apart from any reception it may get at this CG.

All the best,
James

**Comment by dspreadbury** [comment]
James contacted the co-chairs to let them know that he had been working on a wholesale revision of the MNX-Common specification, and the co-chairs responded to ask him to keep his proposals targeted, small and atomic. In proceeding to develop a complete revision of the spec, the co-chairs consider James to be actively working against the interests of the community group, and wish to make it clear that they do not support this work, and they will not even consider any proposals arising from it unless they are made as single, targeted and atomic changes that address only a single aspect. The co-chairs are hereby closing this issue and stating in the strongest terms that they consider James’s work on revising the spec to be completely out of scope for the work of the community group.
