### ISSUE TITLE
Performance/Graphics relationship is N..N, not N..1

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#16]
GMNX currently proposes the use of a `graphics` attribute to reference a [single] graphical element in SVG that gave rise to an `<event>` element in a GMNX `<performance>`. Of course, multiple events may be derived from the same graphic.

This N..1 relationship can break down in numerous cases, since in general some arbitrary set of disjoint (non-grouped) SVG elements could give rise to an arbitrary set of performance events.

As a simple example, consider a sequence of tied CWMN notes at the same pitch. These all yield a single performance event, that is derived from all of the tied notes. That relationship is 1..N.

Another interesting example is a CWMN trilled note. This yields many individual events, each of which might reference both the note and its accompanying trill notation (N..N).

**Comment by joeberkovitz** [comment]
The current spec now supports N..N mappings. An example is given in the GMNX viewer for the Fauré song, in which a pair of tied notes (along with the tie!) are mapped to a single event.

**Comment by mdgood** [comment]
As the chairs believe this issue is resolved, we plan to be closing this issue.
