### ISSUE TITLE
Issues in examples page

### ISSUE THREAD

**Issue by cecilios** [w3c/mnx#160]
The MNX-Common page by example is very useful, but there is a real risk that the proposed examples and images be taken as test cases and mandatory renderizations. In this page introduction it is mentioned that:

> For each example, you’ll see an image of the desired notation, followed by the encoding in MusicXML and MNX-Common.

My understanding of that sentence is that, for each example, the provided MNX encoding should render the provided image. But I'm not sure if this is the goal. If not, I would suggest to put a notice (perhaps a red notice such as the "Not ready for implementation" in the specs. page) clarifying that the images are not the mandatory expected renderization but an illustrative approximation.

In particular I have found several issues. I've preferred to list all them in this issue but I will open an issue for each finding if you prefer. My findings:

1. The documentation for the `mnx` element specifies (in https://w3c.github.io/mnx/specification/common/#the-mnx-element in the Content Model) that the `head` element is required, but none of the examples include a `head`element. Either clarify that `head` element is not mandatory or fix the examples.

2. The systemic barline (the left barline that joins all staves of a system, when the system has measures) is not present in any of the images. Either clarify if systemic barlines must be explicitly encoded or fix the images.

3. In example "Time signatures" the last barline is a final barline. This is not encoded in the provided MNX code. Either, fix the image or the code.

4. The stems in example "Multiple voices" do not follow default stem directions for notes. Instead, some kind of algorithm has been applied. Either a) clarify if any MNX renderer is free to apply such algorithms; or b) specify the used algorithm as part of the MNX standard; or c) change the image so that it depicts the renderization with default stem directions.

Hope this helps.

**Comment by cecilios** [comment]
I forget a last issue:
5. All examples have `<part-name>Music</part-name>` but none of the images render this.

**Comment by adrianholovaty** [comment]
Hi @cecilios — thanks for the excellent feedback! See responses below:

> I would suggest to put a notice (perhaps a red notice such as the "Not ready for implementation" in the specs. page) clarifying that the images are not the mandatory expected renderization but an illustrative approximation.

Great point. I've added a "Not ready for implementation" message in commit 4ecb0512.

> 1. The documentation for the `mnx` element specifies (in https://w3c.github.io/mnx/specification/common/#the-mnx-element in the Content Model) that the `head` element is required, but none of the examples include a `head`element. Either clarify that `head` element is not mandatory or fix the examples.

Good catch there. I've opened a separate issue, #166, for a discussion on making `<head>` optional.

> 2. The systemic barline (the left barline that joins all staves of a system, when the system has measures) is not present in any of the images. Either clarify if systemic barlines must be explicitly encoded or fix the images.
>
> 3. In example "Time signatures" the last barline is a final barline. This is not encoded in the provided MNX code. Either, fix the image or the code.

I've opened issue #165 to have a discussion on these two points, which I consider the same underlying issue (whether barlines should be explicitly encoded). In the meantime, I've added a note to the top of the page in commit 4b6701adca5.

> 4. The stems in example "Multiple voices" do not follow default stem directions for notes. Instead, some kind of algorithm has been applied. Either a) clarify if any MNX renderer is free to apply such algorithms; or b) specify the used algorithm as part of the MNX standard; or c) change the image so that it depicts the renderization with default stem directions.

There was some text in the first example: "The stem directions are not encoded here. This means the consuming program decides which stem direction to use." But since that wasn't clear enough, I've moved it to the top of the page in commit 4b6701adca5.

> 5. All examples have `<part-name>Music</part-name>` but none of the images render this.

Yes, the part-name is considered metadata, as opposed to something that should be rendered.
