### ISSUE TITLE
Specification level

### ISSUE THREAD

**Issue by jacques-menu** [w3c/mnx#164]
Hello,

From my experience, the toughest parts in handling MusicXML data are nested/overlapping part groups, (nested)repeats, nested tuplets and spanners such as ottava shifts.

Did you consider designing MNX-Common top-down from such concepts, instead of bottom-up starting with notes and events?

Jacques Menu

**Comment by adrianholovaty** [comment]
Hi Jacques,

Yes, this was indeed one of the important aspects Joe considered when originally putting together the MNX-Common design. You can check out [the draft spec here](https://w3c.github.io/mnx/specification/common/), and note especially the sections on "Sequence content," "Liaison content," and "Spanning directions."

I'm closing this issue, as it doesn't make a specific suggestion or bug report. Please feel free to open subsequent issues with specific ideas.
