### ISSUE TITLE
Make <head> optional

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#166]
As suggested by @cecilios in issue #160, we should either make `<head>` optional or fix the "MNX-Common By Example" page to include `<head>` elements.

My vote would be to make `<head>` optional, for simplicity. Any thoughts either way?

**Comment by bhamblok** [comment]
Is support the idea of making `<head>` optional.
In fact, I would like to propose a name-change for the `<head>`-element because it conflicts with the `<head>`-element of HTML, when one would include an MNX-file into a website ;-)
Just prefixing would be effective: like `<mnx-head>`?

**Comment by adrianholovaty** [comment]
> In fact, I would like to propose a name-change for the `<head>`-element because it conflicts with the `<head>`-element of HTML, when one would include an MNX-file into a website ;-)

Directly embedding an MNX-Common file within HTML markup is definitely something that _shouldn't_ be done, to be honest. When integrating into a website, I'd suggest loading the MNX-Common file via an Ajax request and keeping it in memory via JavaScript. More broadly, I don't think we should limit MNX-Common element names based on what might conflict with HTML. But this is a separate, off-topic point. :-/

**Comment by adrianholovaty** [comment]
Pull request #170 addresses this.

**Comment by adrianholovaty** [comment]
This is done, as of commit 362b2924.
