### ISSUE TITLE
Clarify alternative vs. sequential elements of collections

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#17]
The current `<collection>` mechanism permits an MNX document to consist of an arbitrary hierarchy of `<score>` elements.

The score elements under any given collection node are presently considered as sequential (e.g. movements of a large work).

However, there are many use cases that would like to encode the idea of _alternative_ elements in a collection, for example variant versions of a work, or a combination of CWMNX and GMNX encodings of the same work.

MNX doesn't have a mechanism to deal with this.

**Comment by adrianholovaty** [comment]
(Closing, as this is handled in a different way by our newer concept of "layouts".)
