### ISSUE TITLE
§5.4 Chromatic Pitch Syntax

### ISSUE THREAD

**Issue by notator** [w3c/mnx#176]
**Preamble**
Before launching into this, I'd first like to say how much I appreciate Joe Berkovitz' contribution to setting up this CG, and the core structures in the Draft Spec. So far, parsing standard MNX-Common is no problem. Its obviously a very powerful proposal. I like the basic feel a lot.
However, I think there is an underlying, low-level confusion between spatial and temporal units in the Draft Spec, and its causing a lot of unnecessary complication. Things could be made a lot simpler, and therefore more powerful by bearing this in mind. Its a problem that's been hanging around since at least the 19th century. Its not just Joe. 
The separation of domains even percolates up to the top level. MusicXML was, very rightly, designed for paper. Live performance practice is something else. SVG or Canvas are spatial formats. MIDI and Audio formats are temporal. (Forget about SVG's animation capabilities - its important that music scores don't move about while we look at them.)

**§5.4 Chromatic Pitch Syntax** in the Draft Spec.
[Begin Edit 09.05.2020]
The following criticism of §5.4 should be read in context of lines like
```
<note pitch="G#4" accidental="sharp"/>
```
or
```
<note pitch="D5" accidental="natural"/>
```
in [MNX-Common by Example](https://w3c.github.io/mnx/by-example/) , Example 6 - Accidentals.
[End Edit]

The introductory description (in Draft Spec §5.4) of how to parse a string denoting a chromatic pitch is unnecessary. Nobody reading the spec needs to be told how to parse a string. Such details depend on what software you happen to be using. The text should be replaced by a strict definition in the form of a _Regular Expression_, perhaps with a short verbal description of what the RegEx means.
I think the current definition, described in the text, is actually wrong. For example, it says that the string can contain an unlimited number of `#`- or `b`-characters, and that the octave is in the range [0..infinity]. The Regex should describe something more like:
```
(1 character in the range [A..G]) +
( either (0, 1 or 2 '#'-characters) or (0, 1, or 2 'b'-characters)) +
(1 character in range [0..9])
```
[Begin Edit]
or, maybe easier:
```
(one character in range [A..G]) +
(one of the strings in { "", "#", "##", "b", "bb"}) +
(one character in range [0..9])
```
(Is octave 10 definitely excluded?)
[End Edit]

This syntax is doing double duty when used as the `pitch` attribute of a `note`.
It describes both an equal-temperament pitch (frequency) and a (context dependent) graphic - the height of a notehead on a staff. Notes with forced accidentals have a separate `accidental` attribute. That's okay, is easy to use, and usually works fine, but it needs watching.
The subsequent definitions
```
C4+0.5 -- The pitch one quarter-tone above middle C

C4+0.25w -- The pitch one quarter-tone above middle C (identical to the above, but expressed in whole tone units)

C4+1/4w -- The pitch one quarter-tone above middle C (identical to the above, but expressed as whole tone fraction)

C4+1/24o --The pitch one quarter-tone above middle C (identical to the above, but expressed as octave fraction)
```
are unnecessarily difficult to parse. And I think its a mistake to provide alternative ways of describing the same thing. That just produces code bloat. These defs should be deleted.
Quartertone accidentals (if they exist in standard MNX-Common) could be defined more easily using something like "q#" for quarterSharp and "qb" for quarterFlat.
[Begin Edit]
The regex would then look like
```
(1 character in range [A..G]) +
(one of the strings in { "", "#", "##", "b", "bb"} ) +
(one of the strings in { "", "q#", "qb"} )
(1 character in range [0..9])
```
[End Edit]
Applications that can't play or display quarter-tone accidentals would simply ignore the "q#" and "qb".

These definitions are good enough for equal temperament, but I think we need a simple way to describe more precise tunings. This could either be in cents above or below the default, equal temperament, tuning, or as an absolute frequency.
Such tunings would simply override the temporal, but not the graphical meaning of the "Chromatic Pitch string".

The counterpart to defining a precise pitch is to stipulate a particular accidental glyph (from the SMuFL repertoire). Implementations would then either have to include the glyph in the font they are using, or use a fallback glyph. How would they know which fallback glyph to use? Have we already found a way to do that?

I think such things are probably easier to realise (and less difficult to parse) than might be thought. So they could all go in the standard MNX-Common profile.

Any thoughts?

[Begin Edit]
MNX-Common by Example may be cast in stone, but I think the `accidental` attribute in
```
<note pitch="G#4" accidental="sharp"/>
```
should perhaps be reconsidered after all.
§6.4.1 says:

> The accidental attribute supplies an accidental value for this note. In the standard MNX-Common profile, this attribute _must match the alteration of the pitch attribute. Omission of the attribute indicates that no accidental is to be displayed._ The special value _auto_ indicates that a consumer application should determine the proper accidental based on musical context.

So this attribute _only_ describes the visibility of the accidental supplied in the string associated with the `pitch` attribute. I can't  think of any reason why we need the `auto` value. Consumer applications should do what they think is correct, regardless of what the XML says, and I can't think of any reason not to use the accidental defined in the `pitch` string.
So I think that complication and potential errors could be avoided if redundancy is avoided in the `accidental` values. The use of non-standard (SMuFL) accidentals could also be simplified if the `accidental` attribute was treated like the CSS `visibility` attribute, and just have the values `visible` and `hidden` (Default is `hidden`). 
{End Edit]

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
