### ISSUE TITLE
Specify "accidental" to overrule the value of "alter" and  having a "no accidental".

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnx#180]
Some time ago I wrote about some problems with MusicXML-files in the collection of the Turkish Makam music. One construction is:

&lt;accidental/&gt;
or
&lt;accidental&gt;&lt;/accidental&gt;

I thought that there was no sense in this, but now I changed my mind. Like you can force a specific accidental to be written, you must be able to force no accidental (nothing) to be written. The value &quot;natural&quot; is not sufficient, because this means remove current sign, defined in the predefined keys or on previous note in the current measure. This writes the natural sign.

There must be a specific accidental saying &quot;no accidental&quot; in order to specify that the value of &quot;alter&quot; e.g. &lt;alter&gt;-0.5&lt;/alter&gt; shall be overruled.

This could be &quot;&lt;accidental&gt;void&lt;/accidental&gt;&quot; (adding &quot;void&quot; to the list of accidentals) or just like it's done in the Turkish Makam songs: &lt;accidental/&gt;

I think that note.mod should be changed - the text from note.mod:
&quot;Actual notated accidentals. Valid values include: sharp,...&quot; 
should be changed to something like: 
&quot;Actual notated accidentals overwrite the values specified by the alter-command concerning the graphic appearance. Valid values are even an empty field (&lt;accidental/&gt;) and include...&quot;

Consequences: There will be no backward compatibility problems since old systems can't handle this anyway.

**Comment by adrianholovaty** [comment]
This is now addressed by our `"support"` key with `"useAccidentalDisplay"` from f3cf6cc20. See #347 for the history/discussion.
