### ISSUE TITLE
Add hint as to whether an accidental has been deliberately displayed or hidden

### ISSUE THREAD

**Issue by mdgood** [w3c/mnx#181]
MusicXML represents whether accidentals appear or not, but nothing indicates if this is a result of applying standard music notation rules, or a deliberate choice to display or hide an accidental. This hint could be helpful for higher-quality exchange between interactive applications doing transposition and other types of formatting. 

This will run into similar problems as a stem direction hint in terms of there being no uniform cross-application definition of a "usual direction". However, like that hint, it can suggest why an engraving is done a certain way, in a form that is both relatively simple and reasonably portable across applications.

Since missing accidentals are omitted from the MusicXML 3.0, a new "none" accidental value may be needed, to be used only in conjunction with a hint that the accidental has been deliberately hidden.

This issue was raised in multiple conversations with MusicXML developers at the NAMM and Musikmesse shows, as well as via private email.

**Comment by mscuthbert** [comment]
Ah -- this has been a recent discussion of the current W3C group for MNX (@adrianholovaty and @dspreadbury) and something we've been taking up in the talk on #288 .  The reason why idea is still relevant.  (music21's accidental.displayStatus vs accidental.displayType might be useful here).
