### ISSUE TITLE
"son" - Proposal for a music subroutine.

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnx#189]
"son" - a musical subroutine.

It is easier to make something from the beginning, than later. My proposal is to add a "musical subroutine" like done in the makam-music. The image shows how this is done in the Makam-music, where "son" is a return statement.

The start of the subroutine is marked with Segno. The return is marked with the text "son". My proposal is to add a "son" symbol in the group with "fine", "dal segno" etc. When "son" comes a jump is made to after "dal segno" (D.S.)

You see the need for this structure in Beatles songs, Jazz songs etc.. The music-subroutine could be useful everywhere a refrain comes in different places in the music.

Music words are already of different languages - so why not just "son"?
  
![Tyrkisk](https://user-images.githubusercontent.com/3636047/87172587-c019e800-c2d4-11ea-8812-881d05e60e73.jpg)

**Comment by adrianholovaty** [comment]
Thanks for the proposal, @mogenslundholm. I think that's an interesting idea worth purusing at some point in the future. For now, we'd like to focus MNX-Common on handling existing musical notations as opposed to creating new ones. Could you bring this back to the group once we've reached the first stable release of MNX-Common?
