### ISSUE TITLE
Remove concept of "profiles"

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#192]
The MNX spec currently has a concept of profiles (see [here](https://w3c.github.io/mnx/specification/common/#element-attrdef-mnx-common-profile)), with only a single profile defined at the moment: "standard."

I'd like to remove this.

The intent of profiles was to help narrow the scope of what applications can expect to have to deal with. We can solve this issue in another way — by documenting/specifying exactly what applications should do in certain situations, along with providing sensible defaults.

For example, the spec [currently says](https://w3c.github.io/mnx/specification/common/#the-note-element) the "standard" profile introduces the constraint that the `<note>`'s `accidental` attribute must match the alteration of the `pitch` attribute. Instead of relying on profiles for this, we could just change the spec to say one of the following:

* The `accidental` must *always* match the alteration of the `pitch` attribute; otherwise it's an invalid MNX document.
* The `accidental` must not necessarily match the alteration of the `pitch` attribute; if it doesn't, we provide a precise definition of what this is intended to mean and how it should be interpreted.

Overall the goal of this would be to simplify and reduce the number of variables a developer has to contend with when consuming an MNX file. Some other prior art is MusicXML's `<supports>` element, which I believe @mdgood would say was not a good idea in retrospect; anecdotally we know that very few programs actually use that data or treat it as reliable/actionable.

**Comment by adrianholovaty** [comment]
Forgot to include the relevant [notes from our last co-chair meeting](https://www.w3.org/community/music-notation/2020/08/04/co-chair-meeting-minutes-august-4-2020/), as they add some extra context to this:

> As part of the naming discussion, there were a number of discussions concerning the idea of profiles, which were proposed as part of the original MNX-Common design as a means of declaring what kinds of notations can be expressed by a particular document, with a view to allowing applications to support different “levels” of MNX-Common.
>
> However, as work on the specification continues, the co-chairs now feel that as part of the constant drive to keep MNX-Common focused on practicality, intelligibility and ease of use, profiles are contrary to those goals. The co-chairs believe that we can do away with the concept of profiles, provided we always specify precisely what the default behaviour for every kind of encoding should be, and take the hard decisions about precisely what can and cannot be encoded in MNX-Common. Adrian will create an issue for community discussion around this point.

**Comment by notator** [comment]
@adrianholovaty The Co-chair Meeting Minutes August 18, 2020 say that you have completed the work necessary for renaming MNX-Common to MNX but, as far as I can see, all you have done is to rename the [MNX Draft Specification](https://w3c.github.io/mnx/specification/common/) and [MNX by Example](https://w3c.github.io/mnx/by-example/) files. In particular, you have not renamed the MNX-Common element inside the MNX Draft Spec.

Statements such as
> The MNX spec currently has a concept of profiles...

and (@samuelbradshaw in https://github.com/w3c/mnx/issues/177#issuecomment-677842143):
> Ideally, a solution in MNX would allow lyrics to be independent from parts,...

are therefore logically correct but confusing. They actually refer to the MNX-Common object that is defined inside the MNX Draft Spec. MNX is _still_ the name of a specification that _contains_ MNX-Common. It is not the MNX-Common specification itself. 

If the co-chair really wants MNX to be a "deliverable" file format (extension ".mnx") that replaces MNX-Common, then the [MNX Draft Spec](https://w3c.github.io/mnx/specification/common/) needs to be edited accordingly:
   - remove the existing MNX object
   - rename the MNX-Common object to MNX.

Assuming that this has been done, and MNX is the file format (extension ".mnx") that succeeds MusicXML, then I also think it would be a good idea to get rid of profiles. I agree with the co-chair that its important to be able to tell what the file is supposed to accomplish (and which applications can use it) by looking at its file extension. Possibly there can be a few switches of the kind @adrianholovaty describes above, but there are limits to what this strategy can accomplish. It would be better to define separate file formats (with corresponding extensions) for notations that cannot be described efficiently as variations of MusicXML. These could well share code with the MNX file format itself.

Such a drastic revision of the MNX Draft Spec also needs to be reflected in a revision of the [Group Charter](https://www.w3.org/community/music-notation/wiki/Group_Charter). The definition of MNX and the "Deliverables" section especially need attention. The new Group Charter, should
   - more accurately reflect the de-facto interests and intentions of the participants in this group.
   - incorporate the results of the discussions we have had over the past few years.

I think we are currently being held up by obsolete objectives and an undefined road map, and that an honest redefinition of the Group Charter would go a long way to resolving that impasse.

**Comment by adrianholovaty** [comment]
@notator Thanks for the comment and for pointing out the charter needs to be updated — we will indeed have to update the charter (and likely other bits as well)!

**Comment by adrianholovaty** [comment]
Closing this now that pull request #201 has been merged.
