### ISSUE TITLE
Slurs and Ties

### ISSUE THREAD

**Issue by notator** [w3c/mnx#203]
I've recently been working on the _MNX by Example_ **slur** and **tie** examples in my [MNXtoSVG](https://github.com/notator/MNXtoSVG) application, and have some proposals:

**Proposal 1:** The `<tied>`element should be renamed `<tie>`.
This element is a graphical object. To paraphrase @adrianholovaty's comment about `<beams>` in [#198 (comment) Proposal 1](https://github.com/w3c/mnx/issues/198#issuecomment-717210494):
> There is a one-to-one mapping between a [`<tie>`] rendered in notation and a [`<tie>`] element. This is conceptually elegant, and it gives us a place to add additional [`<tie>`]-specific metadata.

The use of `<tied>` obviously comes from MusicXML, which uses `<tie>` to describe [the _sounding_ part of a tied note](https://www.musicxml.com/tutorial/the-midi-compatible-part/tied-notes/#:~:text=The%20tie%20element%20has%20a,%E2%80%9D%3E%20to%20the%20next%20note.) (i.e. its temporal aspects), and `<tied>` to describe [the notated tie](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-tied.htm?Highlight=tied) (its spatial aspects).
The current MNX debate is _only_ about the notated objects. (As I've said before, I think we should get those sorted out before tackling temporal information.) I think that using `<tie>` to describe the notated object in MNX would be far better in the long run, and unlikely to cause a problem when we start thinking about time. 

**Proposal 2**: The `<tied>` `target="noteID"` attribute is redundant and should simply be omitted.
The target note must _always_ be in the following `<event>` in the voice, and have the same pitch as the original tied `<note>`, so we don't need the ID.

**Proposal 3:** `<tied>` should, like `<slur>`, have a `side` attribute, and it should be _compulsory_ in both cases.
The application that _writes_ the MNX code knows which way up the slurs or ties are, so _writing_ the value of the `side` attribute should never be a problem. But deducing the `side` from the MNX context is both difficult and error-prone: The rules for ties are complicated, especially when there are several voices on a staff, and/or noteheads are on different sides of stems. Users can only really be guaranteed to get out what they put in if the `side` is written out explicitly.

**Proposal 4:** The `<slur>` and `<tie>` `incoming`, and `outgoing` attributes could be deleted.
I can see no use for these, and suspect that they are a left over from MusicXML's "score-timewise" format. In MNX, slurs and ties are always defined in a "part-wise" context, so its always clear where they are going. Ties that end without a target note are used for _laissez vibré_ indications (that are always horizontal), but these can easily be defined using a proper measure location in the `<tied> location` attribute. (Note that it is then possible to define whether or not a _laissez vibré_ tie is repeated if it crosses a system boundary: it will do so if it crosses a barline, otherwise not.) 

**Proposal 5:** Changes to [§5.5 Measure location syntax](https://w3c.github.io/mnx/specification/common/#measure-location)
[§6.7.2](https://w3c.github.io/mnx/specification/common/#the-slur-element) says:
> If `target` is not provided, the `<slur>` does not connect to a particular destination `<event>`. In this case, the `location` attribute may be used to specify the measure location of the other end of the `<slur>`.

So I think the location attribute (Measure location syntax) should only be used if there is no target attribute and no destination event at the given location. That means that Case 3 in [§5.5](https://w3c.github.io/mnx/specification/common/#measure-location) never happens, and the Measure location syntax should not include event IDs.
The syntax includes a _measure location_ if the `location` is not in the measure in which the `<slur>` or `<tied>` started. (So the `location` is always in the voice in which the `<slur>` or `<tied>` started.)
Contrary to the spec, I think the syntax would be simpler to use if the "measure" in the §5.5 syntax were _relative to the current measure_, not the absolute measure number.

**Proposal 6:** Avoid using IDs where possible
This is more or less what I was suggesting in point 4 of https://github.com/w3c/mnx/issues/193#issuecomment-691708030.
That proposal is very similar to the current Measure location syntax, but uses event numbers (indices) instead of metrical event positions.
Contrary to using IDs, I think indices remain easy to use even when the number of events in the file increases...
Avoiding the use of IDs where possible enables plausibility checking, makes the code more expressive for human readers, and reduces both file sizes and coding overhead.

**Comment by adrianholovaty** [comment]
Sorry for taking a while to respond to this, but in the future could you please create a _separate_ issue for each idea rather than a single issue containing six proposals?

Proposal 1 (rename `<tied>` to `<tie>`): I've created #256 to collect feedback on this.

Proposal 2 (remove the `<tied>` `target` attribute): I've created #257.

Proposal 3 (`<tied>` should have a "side" attribute): I've created #258.

Proposal 4 (`<slur>` and `<tie>` `incoming`, and `outgoing` attributes could be deleted): I've created #259.

Proposal 5: I'm not 100% sure what you mean, so could you open a new issue with this if it's still relevant?

Proposal 6 (avoid using IDs): I'm afraid this is a non-starter. IDs are useful for all sorts of purposes.

(Marking this as closed; please comment on the new issues and keep issues focused and atomic. Thanks!)
