### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by benbankes** [w3c/mnx#204]
I assume that MNX is xml, since much of the discussion in this repository includes angle brackets and references to "elements".  If that is the case, this comment may come way to late.

I would like to see a interoperable music notation format represented in JSON.

Using JSON instead of XML could create a boon in digital music, by lowering the effort required to create music-based applications, since many programming languages can easily use JSON.

**Comment by adrianholovaty** [comment]
@benbankes Thanks for this. Yes, MNX is indeed an XML format. You can see some full examples in [MNX By Example](https://w3c.github.io/mnx/by-example/).

Personally I vastly prefer JSON to XML — the former is much easier to work with. Alas, in the words of Austin Powers, "the train has sailed" for MNX. The decision was made to use XML several years ago, and it's too late to change the format in such a fundamental way.

With that said, I believe there are various libraries to consistently convert XML into JSON representations. If the parsing part is what you find annoying about XML, you might want to use an intermediary tool like that. I'm reasonably sure some notation applications are already doing this for MusicXML.
