### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by notator** [w3c/mnx#214]
This issue continues the discussion in Pull Request #190 (which I think should now be rejected and closed).

**Summary of the discussion in #190:**
- Custom HTML entity strings can be defined in MNX. (see @ahankinson's https://github.com/w3c/mnx/pull/190#issuecomment-748930959)
For example: `<!ENTITY segno CDATA "&#x1D10B;" >` at the top of a file defines the `&segno;` entity string to mean the segno character. In future, I'll be using such entity strings, without further comment, as if this has been done.
- References to local IDs should begin with a '#' character (see @ahankinson's https://github.com/w3c/mnx/pull/190#issuecomment-748117620). **Edit 29.08.2021:** I've changed my mind on this. References to local IDs should _not_ begin with a '#' character. See https://github.com/w3c/mnx/issues/57#issuecomment-896625535.
- There is an issue with multi-line text (see https://github.com/w3c/mnx/pull/190#issuecomment-748453764 and https://github.com/w3c/mnx/pull/190#issuecomment-748589825).
I'm proposing the use of two new elements: `<text>` and `<textBlock>`, both of which need defining more precisely. The `<text>` element would replace [the `<instruction>` element in the Draft Spec](https://w3c.github.io/mnx/specification/common/#elementdef-instruction).
- Apropos https://github.com/w3c/mnx/pull/190#issuecomment-741691052 about mid-measure repeats:
![midMeasureRepeats](https://user-images.githubusercontent.com/1655500/103769541-c5a67f80-5024-11eb-9bb6-819ae3921b7a.png)
MusicXML's treatment of [repeat signs as barline types](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-repeat.htm) means that it has to use a hack to implement mid-measure repeats. Both of [its available codings](https://github.com/w3c/mnx/pull/190#issuecomment-741369239) lead to confusion about what is and is not a measure, and consequently to confusion about the measure numbers, so they are clearly inferior to _not_ treating repeat signs as barlines in the first place. I therefore disagree with @adrianholovaty 's https://github.com/w3c/mnx/pull/190#issuecomment-741703318 that "no special markup would be needed for this case". This example still has to be added to _MNX by Example_, and should, as always, contain both the MusicXML and the MNX code.
- I'm proposing that a `<switch>` element be defined, containing an ordered list of _actions_ to be taken when the `<switch>` is encountered _during a performance_. Note that `<switch>` elements are not rendered graphically, and can safely be ignored by non-performing applications. (I've always been looking for a better name for this element, and am going to rename it again below. Names are important.) 
[My final comment in #190](https://github.com/w3c/mnx/pull/190#issuecomment-754579572) lists the (currently proposed) possible actions as
   -  goto somewhere
   -  continue
   -  pause 
   -  stop.
---

**Further thoughts:**

First, I'd like to rename `<switch>` (aka `<jump>`) to `<actions>`. This makes the element's _type_ more obvious and precise since, in addition to having a _location in the score_, it contains an ordered list of _action_ elements, each of which is a non-printing, _imperative verb_ that has to be executed at a particular _time_.

Begin Edit 9 Jan., 2021
I'd also like to define a new `<action>` (singular) element. The two definitions look something like this:
1. The `<actions>` element contains an ordered list of _two or more_ action elements that define a stack of actions. Each time the `<actions>` element is invoked, the action on the top of the stack is executed and then popped off the stack. If the stack is empty, the `<actions>` element does nothing.
2. The `<action>` element contains exactly _one_ action element that is executed each time the `<action>` element is invoked.

End Edit 

Clearly differentiating between graphic and temporal information leads to a much simpler and considerably more powerful way to code repeats and jumps, so the current `<repeat>` and `<ending>` elements, and all printed texts (such as `"dal Segno"`, `"&segno;"`, `"Da capo als segno"` etc.) have to be considered to be purely graphical objects.

Of course, it _may_ be possible to infer a behaviour from the graphics, but the following problems arise:
- A performing application _may_ be unable to interpret the graphics. This will, for example, be the case when dealing with unknown accidentals (see the discussion with @cmloegcmluin in #184)
- The graphics may mean different things at different times. This is the case when dealing with 1st, 2nd, 3rd time etc repeat measures, or when a simple repeat is supposed to be played louder, slower etc than the first time through.

As will be seen in the **_accel._** example below, its easy to define specialised actions for purposes other than repeats and jumps. If there is consensus that I'm on the right track here, we could well be doing that over the next few weeks, but my primary objective is to create a revision of the current _MNX by Example_ examples and the _Draft Spec_ that can be presented as a Pull Request before the next co-chair meeting (19th January). 

---

**Examples:**

The Repeat examples in _MNX by Example_ are still okay, but should be considered to contain only graphic information. As discussed in #190, the Jump examples in _MNX by Example_ need revising. The Jump examples in #190 are, I think, more or less okay, but the `<jump>` elements there need to be renamed `<actions>`.

The following examples are only supposed to demonstrate the _principle_ behind using `<actions>`  and `<action>` elements. Any new actions they may _use_ are placeholders, not precise proposals. Feedback would, of course, be very welcome!

The simplest one-time repeat
![simpleRepeat](https://user-images.githubusercontent.com/1655500/103769062-ec17eb00-5023-11eb-9f13-4e76653e9a18.png)
would be coded, using an `<actions>` element, like this:
```
<mnx>
    <global>
        <measure>
            <directions>
                <time signature="4/4"/>
                <repeat id="startRepeat1" type="start"/>
                <repeat type="end"/>
                <actions location="4/4">
                    <goto target="#startRepeat1" />
                    <stop />
                </actions >
            </directions>
        </measure>
    </global>
    ...
</mnx>
```

Notes:
- The `<stop />` is compulsory because an `<actions>` element must contain at least two action elements. A `<continue />` would be used for a repeat that is not at the end of the score.
- using an `<action>` element here would result an endless loop.
```
                <action location="4/4">
                    <goto target="#startRepeat1" />
                </action >
```

A varied repeat:
![FthenP_Repeat](https://user-images.githubusercontent.com/1655500/103891317-e8e73280-50e9-11eb-8f1e-53f9fd11fa2c.png)
```
<mnx>
    <global>
        <measure>
            <directions>
                <time signature="4/4"/>
                <repeat id="startRepeat1" type="start"/>
                <text location="0" string="&forte;, 2nd time &piano;" orient="down" />
                <actions location="0">
                    <continue>
                    <masterVolume value="50%" />
                </actions >
                <repeat type="end"/>
                <actions location="4/4">
                    <goto target="#startRepeat1" />
                    <stop />
                </actions >
            </directions>
        </measure>
    </global>
    ...
</mnx>
```

An **_accel_** would be coded using an `<action>` (singular) element:
![accel](https://user-images.githubusercontent.com/1655500/103891349-f69cb800-50e9-11eb-88b2-9285fdea99cc.png)
```
<mnx>
    <global>
        <measure>
            <directions>
                <time signature="4/4"/>
                <text location="1/8" string="accel." orient="up" >
                    <extender duration="7/8" class="accelDashes" />
                </text >
                <action location="1/8" >
                    <speedChange factor="200%" type="linear" duration="7/8" />
                </action >
            </directions>
        </measure>
    </global>
    ...
</mnx>
```

This is the usual way to code actions that happen once. But note that if this example was contained in a repeat, the `<speedChange>` would be executed every time the `<action>` was invoked, and the performance would continue to accelerate.
 
---

**Issues:**

Some `<text>` elements, such as **_accel._**, don't need to be printed in every part in a score, but would be needed when extracting parts. Possibly, in a score containing many parts, the `<text>` could be defined separately in each part that requires it, but the rules governing global `<text>` still need to be worked out. This may also involve being more precise about our use of global and local CSS.
Note the different behaviour of `<repeat>` and `<ending>` elements. These must be printed in _all_ `<part>`s, both in the full score and in the individual part-booklets, so they don't need `<part>`-specific CSS.

Each of the available action types (=elements) needs to define precisely how and where it can/should be coded. For example, a `<speedChange>` can only be global, but `<part>`s should probably be allowed to have individual changes of dynamic: In a repeated measure having two parts, one part could have "&forte;, 2nd time &piano;", while the other has "&piano;, 2nd time &forte;".

Comment & suggestions welcome.

**Comment by bhamblok** [comment]
I'd like to comment on your proposal of the `<text>`-element.
Wouldn't it be nicer if we put the value of the "string"-attribute simply as content of the element?
```xml
<text location="0" orient="down">&forte;, 2nd time &piano;</text>
```
and
```xml
<text location="1/8" orient="up" >
    accel.
    <extender duration="7/8" class="accelDashes" />
</text >
```

**Comment by notator** [comment]
@bhamblok Thanks for the feedback! :-). I'm in the process of moving the debate about text into its own issue, so will reply to you there when I post it. Should be ready soon.

I've now updated my original posting to this issue (_Actions_) to include a proposal for a new `<action>` (singular) element.

**Comment by notator** [comment]
The `<action>` element is redundant. See https://github.com/w3c/mnx/issues/217#issuecomment-761548580

**Comment by notator** [comment]
I'd like to define the way the `<actions>` element works more precisely, and thereby make a small change:
1. The contained list of actions defines a _stack_ of actions.
2. Each time the actions element is reached during a performance, the action at the top of the stack is performed, and then popped of the top of the stack.
3. When the stack is empty, no action is performed.

This means that
-  the <stop /> is unnecessary in https://github.com/w3c/mnx/issues/216#issue-784966091 since the action is at the end of the file
- it is always unnecessary (but harmless) to define a `<continue>` action at the bottom of the stack.

Summary: I think the following actions are basic
- `<goto target=... />`
- `<continue />`
- `<pause 7>`
- `<stop />`

and that, after proper discussion, further actions are likely to be defined in future (for example something like `<speedChange>` in the **_accel._** example above.)

**Comment by adrianholovaty** [comment]
Closing an outdated issue.
