### ISSUE TITLE
Texts

### ISSUE THREAD

**Issue by notator** [w3c/mnx#215]
This issue is a branch of the _Actions_ Issue #214, which originated in Pull Request #190.
I'm moving the debate about Texts here, since they are purely graphical objects, independent of Actions.

#### Text issues that originated in #190

- **Multi-line Text**: There is an issue with multi-line text (see https://github.com/w3c/mnx/pull/190#issuecomment-748453764 and https://github.com/w3c/mnx/pull/190#issuecomment-748589825).
I'm proposing the use of two new elements: `<text>` and `<textBlock>`, both of which need defining more precisely. The `<text>` element would replace [the `<instruction>` element in the Draft Spec](https://w3c.github.io/mnx/specification/common/#elementdef-instruction).
- **Texts in full scores and part booklets**: Some `<text>` elements, such as **_accel._**, don't need to be printed in every part in a full score, but would be needed when extracting parts. Possibly, in a score containing many parts, the `<text>` could be defined separately in each part that requires it, but the rules governing global `<text>` still need to be worked out. This may also involve being more precise about our use of global and local CSS.

I provisionally used the following `<text>` elements as placeholders:
```
<text location="0" string="&forte;, 2nd time &piano;" orient="down" />
```
and
```
<text location="1/8" string="accel." orient="up" >
    <extender duration="7/8" class="accelDashes" />
</text >
```

@bhamblok asked:
Wouldn't it be nicer if we put the value of the "string"-attribute simply as content of the element?
```
<text location="0" orient="down">&forte;, 2nd time &piano;</text>
```
and
```
<text location="1/8" orient="up" >
    accel.
    <extender duration="7/8" class="accelDashes" />
</text >
```
---
@bhamblok Thanks again for the feedback! :-)

I basically agree with you. The full answer to your question emerges below while thinking about the **Multi-line texts** issue (and which text classes we need to define), but first, I'd like to make a note of some housekeeping that needs to be done:

**[§6.8 of the Draft Spec](https://w3c.github.io/mnx/specification/common/#common-direction-content) needs updating:**
- the following elements are redundant (MusicXML was created before we had HTML entities):
  - [§6.8.2 the _dynamics_ element](https://w3c.github.io/mnx/specification/common/#the-dynamics-element)
  - [§6.8.4 the _expression_ element](https://w3c.github.io/mnx/specification/common/#the-expression-element)
  - [§6.8.7 the _coda_ element](https://w3c.github.io/mnx/specification/common/#the-coda-element)
  - [§6.8.8 the _segno_ element](https://w3c.github.io/mnx/specification/common/#the-segno-element)
  - [§6.8.10 the _symbol_ element](https://w3c.github.io/mnx/specification/common/#the-symbol-element)
  - [§6.8.11 the _dirgroup_ element](https://w3c.github.io/mnx/specification/common/#the-dirgroup-element)
- the following elements need to be updated
  - [6.8.5 the _ending_ element](https://w3c.github.io/mnx/specification/common/#the-ending-element) 
  - [6.8.6 the _repeat_ element](https://w3c.github.io/mnx/specification/common/#the-repeat-element) 
- we are currently replacing [§6.8.3 the _instruction_ element](https://w3c.github.io/mnx/specification/common/#the-instruction-element) by more flexible/powerful text elements.
- the comment under [§6.8.9 the _harmony_ element](https://w3c.github.io/mnx/specification/common/#the-harmony-element) should be changed to
"_Needs migration from MusicXML (create a specialised _text_ element for this)._".

The **Multi-line Text** issue:
We first have to agree on the basic text classes. Do we pack everything into a single <text> element? If not, which text types need their own element?
My current feeling is that _five_ basic text elements need to be defined:
- `<text>` // a single line of text (e.g. "da Capo")
- `<textBlock>` // a block of text containing one or more lines
- `<extendedText>` // contains a single line of text and an `<extender>` line (e.g. ![accelText](https://user-images.githubusercontent.com/1655500/104165104-37057a00-53f9-11eb-95bc-6dda7b51c038.png))
-  `<bracketedText>` // contains a single line of text with a `<bracketHook>` on either side (e.g. ![triplet](https://user-images.githubusercontent.com/1655500/104164530-5354e700-53f8-11eb-8824-67e40eec6973.png))
- `<harmony>` // replicates the behaviour of [MusicXML's `<harmony>` element](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-harmony.htm#:~:text=The%20harmony%20type%20is%20based,harmony%20elements%20differentiated%20by%20type.). (See also: [the Draft Spec](https://w3c.github.io/mnx/specification/common/#the-harmony-element))

These would all have [common Direction attributes](https://w3c.github.io/mnx/specification/common/#common-direction-attributes), an (optional) `id` and (compulsory) `class` attributes.
- the `id` can be the `target` of a `<goto>` action.
- The (quasi CSS) `class` attribute identifies the element's "appearance-class" (see below).

BTW: - This makes the `<target>` element in [my original Jumps proposal](https://github.com/w3c/mnx/pull/190#issuecomment-747404616) superfluous since it can be implemented using something like `<text id="segno1" ... >&segno;</text>`.

**_Proposal_**: A `<textBlock>` should be an ordered list of nested `<text>` elements, in which each single-line string is a  `<text>` element's _content_ &mdash; not an attribute. (Agreed with @bhamblok.)
For example, a single line text would be:
```
<text class="partInstruction" location="0" orient="down" >&forte;, 2nd time &piano;</text>
```
While a multi-line text block would be
```
<textBlock class="partInstruction" location="0" orient="down" alignment="left">
    <text>&forte;</text>
    <text>2nd time &piano;</text>
    <text>3rd time &pianissimo; cresc. al &fortissimo;</text>
</textBlock>
```
Notes:
- Classes (I'd particularly welcome some feedback here. CSS is not my strong point.):
   - I think the classes should remain undefined in MNX. If that's the case, then client applications have to supply the definitions. Having such class identifiers in MNX simply ensures that consistent styles can be  applied to the same kinds of text.
   - I think it might be a good idea to define a set of standard class names. Applications could then expect to supply different definitions for "partInstruction", "globalInstruction" etc.
   - Could such class strings contain multiple classes here? For example: `class="bold italic part instruction"`.
   - The text classes should, of course, cascade: the class of a nested `<text>` should override its `<textBlock>`'s class.
- Emphasis: I think the text string should support [emphasis markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#emphasis), at least for bold and italic text. Should we support strikethrough and/or underline?

Using this general strategy, the `<extendedText>` element could be defined as a container, containing a (single) `<text>` element and an `<extender>` line definition:
```
<extendedText location="1/8" orient="up" >
    <text class="bold italic part instruction">accel.</text> <!-- issue with the class string... -->
    <extender duration="7/8" class="globalAccelDashes" />
</text >
```

The answer to the **Texts in full scores and part booklets** issue may involve the `<staffGroup>` elements in [my proposal for how to group parts](https://github.com/w3c/mnx/issues/185#issuecomment-643174127), which [the co-chair accepted last June](https://www.w3.org/community/music-notation/2020/07/07/co-chair-meeting-minutes-july-7-2020/) but which still needs to be integrated into _MNX by Example_ and the _Draft Spec_.
So I need to refresh my memory about that, and this posting is quite long enough anyway, so I'll save that topic for another posting.

**Comment by notator** [comment]
Added a fifth basic text type ( `<bracketedText>`) to the above posting.

Actually, I think it would be a good idea to treat `<bracketedText>` as being _abstract_ (i.e. without a defined element), and to regard the existing `<tuplet>` element as a concrete sub-class thereof.
This would leave the [_Tuplet_ example in MNX by Example](https://w3c.github.io/mnx/by-example/#tuplets) unchanged, and the responsibility for the graphic implementation with the consuming application. (Note that tuplets are only ever added to _parts_, so there's no need to sub-class the `<tuplet>` element with a `class` attribute.) 
A `<tuplet>`'s `outer` and `inner` attributes are needed in order to draw the graphics correctly, but that leaves its _temporal meaning_ undefined. The _default_ durations of the enclosed `<event>`s _might_ be calculated from the total duration of the `<tuplet>` and the values of the `inner` and `outer` attributes, but:
1. We ought to take the granularity of computer time (_ticks_) into account when defining durations.
(Durations needs to be dealt with in their own issue.)
2. It should be possible to save an arbitrary tick duration inside each `<event>`, providing that the ticks add up in each `<measure>` and each (nested) `<tuplet>`. This would enable temporal styles (_swing_ etc.) to be stored directly, rather as is done in ordinary recordings. 

As in #184, not all temporal info needs to be stored in `<action>` or `<actions>` elements. In this case, I think a simple (optional) duration attribute would be best. Assuming that the duration of a tick has been defined earlier (e.g. 1 tick = 1 millisecond), a `<tuplet>` containing non-default durations would look something like this: 
```
                <tuplet inner="3/8" outer="2/8" duration="1000">
                    <event value="/4" duration="700">
                        <note pitch="C5"/>
                    </event>
                    <event value="/8" duration="300">
                        <note pitch="G4"/>
                    </event>
                </tuplet>
```

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
