### ISSUE TITLE
MIDI

### ISSUE THREAD

**Issue by notator** [w3c/mnx#216]
There could be a (temporal) `<midi>` element (like `<actions>`), that would send all its messages "simultaneously" (rather than one at a time):

The simplest one-time repeat
![simpleRepeat](https://user-images.githubusercontent.com/1655500/103769062-ec17eb00-5023-11eb-9f13-4e76653e9a18.png)
could be coded, using `<midi>` and `<actions>` elements, like this:
```
<mnx>
    <global>
        <measure>
            <directions>
                <!-- the following two elements define a default "tempo" of 60 quarters per minute -->
                <ticksPerQuarter value="1000" /> <!-- constant for the whole score (could be some other value) -->
                <millisecondsPerTick value="1" /> <!-- changing this later would change the default "tempo" -->

                <target id="target1" location="0" />
                <repeat type="start"/>
                <repeat type="end"/>
                <actions location="4/4">
                    <goto target="#target1" />
                    <stop />
                </actions >
            </directions>
        </measure>
    </global>
    <part>
        <part-name>Music</part-name>
        <measure>
            <sequence>
                <directions> <!-- moved here from the enclosing <measure> -->
                    <clef sign="G" line="2"/>
                    <time signature="4/4"/> <!-- moved here from <global><directions> -->
                </directions>
                <midi>
                    <msg  b1="0x90" b2="72" b3="127" /> <!-- NoteOn, channel 0, C5, volume=127 -->
                    <!-- etc., more messages -->
                </midi>
                <event value="/1" duration="4010"> <!-- duration override -->
                    <note pitch="C5"/>
                </event>
                <midi>
                    <msg  b1="0x80" b2="72" /> <!-- NoteOff, channel 0, C5, default volume -->
                    <!-- etc., more messages -->
                </midi>
            </sequence>
        </measure>
    </part>
</mnx>
```
My instinct is to put the `<midi>` elements between the `<part><measure><sequence><event>` elements (as above).
The elements that set the default "tempo" in `<global><measure><directions>` also need to be discussed.

**Comment by notator** [comment]
Thinking more about this, I now want to put `<midi>` elements inside each `<event>`.
If the first and last elements inside an `<event>` can be a `<midi>` element, the code would look like this:
   ```
 <part>
        ...
        <measure>
            <directions>...</directions>
            <sequence>
                <event ... >...</event>
                <!-- more events etc. -->
                <event value="/1" duration="4010"> <!-- duration override -->
                    <midi>...</midi>
                    <note pitch="C5"/>
                    <!-- more notes -->
                    <midi>...</midi>
                </event>
                <!-- more events etc. -->
            </sequence>
        </measure>
    </part>
```
The messages in the first `<midi>` element in an `<event>` would be sent immediately _after_ the last messages in the previous `<event>` (if any). They occur at the same logical time, but the order can still be important.
Also, the duration of an `<event>` (= the duration between its two possible `<midi>` elements) is known before the `<midi>` elements are parsed, which looks better.

To be clear:
- If the score contains any MIDI information at all, then the first `<midi>` element would be compulsory, and the second  optional.
- All `<midi>` elements can be ignored by non-MIDI applications.

**Comment by ahankinson** [comment]
For reference, you may be interested in checking out how [we do this in MEI](https://music-encoding.org/guidelines/v4/content/integration.html#midiGuidelines).

**Comment by notator** [comment]
Thanks for the link!

Re MEI's **14.5.1. PPQ in scoreDef and staffDef**:
I'd like to propose that MNX uses tick-based timing, not PPQ as in MEI and our current Draft Spec.
Its very easy to calculate time-stamps from ticks and their durations, and tick-based timing interfaces well with  _all_ performing applications, not just (web) MIDI applications. I'll open a new issue on the subject after I've posted here.

Re MEI's **14.5.3. Recording MIDI Event Data** and **14.5.4. MIDI in Mensural and Neume Notation**:
I used low-level `<midi><msg>` elements [above](https://github.com/w3c/mnx/issues/216#issue-784966091), but MEI uses `<midi><cc>` elements.
That implies that we could not only define a separate element for each MIDI command:
- `<noteOff>`
- `<noteOn>`
- `<aftertouch>`
- `<cc>`
- `<programChange>`
- `<channelPressure>`
- `<pitchWheel>`

but also 
- `<pitchWheelSensitivity>`

elements describing continuous transformations (like the `<action><speedChange>` element in the **_accel._** example in https://github.com/w3c/mnx/issues/214#issue-781321815).
- `<afterTouchEnvelope>`
- `<channelPressureEnvelope>`
- `<pitchWheelEnvelope>`

and an element that describes the sequence of notes/chords in an _ornament_ (such as a trill):
- `<ornament>`

(Note that ticks can be used as time-stamps in temporal sequences.)

Re MEI's **14.5.3. Recording MIDI Event Data**
MEI deprecates the use of `<noteOn>`, but MNX doesn't use MEI's `<note>` element, so that's probably not relevant here. @ahankinson: Is it relevant?

**Comment by ahankinson** [comment]
The MIDI "note on" event is used to trigger a pitch at a given time, which is precisely what the `<note>` element is meant to indicate. So it was redundant to have both. I'm assuming MNX has the same capabilities (triggering a specific pitch at a given time) so it would also seem redundant to have both? Not sure. Using the same for both would mean there would be less of a chance that they might get out of sync, or have conflicting information.

MEI has a number of different ways of indicating the performed tempo; ppq isn't the only way. We also have the `@midi.mspb` which is the microseconds per quarter note. The easiest way of seeing all the options might be by consulting the documentation for the `<scoreDef>` definition here: https://music-encoding.org/guidelines/v4/elements/scoredef.html

As I understand it, that's similar to your proposal except that it uses a fixed unit (the quarter note). And it's measured in microseconds, not milliseconds. 

For MEI, the goal was not to encode MIDI in XML, but to have enough flexibility to capture data from a MIDI file, and to ensure that there can be a round-trip back to the same MIDI data so that nothing was lost in the conversion. It seems like your proposal above, however, is to provide a parallel encoding of notation data -- one in MIDI, and the other in MNX.

**Comment by adrianholovaty** [comment]
This feels very out of scope for MNX. Given the elements already present in MNX, it's already possible to generate playback information — including answering the questions "which notes are played exactly together" and "how long should these notes last"?
