### ISSUE TITLE
Migrate spec and "By Example" to new docs system

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#223]
This GitHub issue serves as a general holding place for remaining to-dos in migrating our docs.

As of 2021-01-21, the doc system is still in progress but is already capable of:

* Displaying list and detail pages for elements, examples, data types and concepts
* Allowing editing of all that data, via the Django admin
* Serializing/deserializing the raw database to a JSON file
* Generating a static HTML version of the docs

See the [docgenerator README](https://github.com/w3c/mnx/tree/master/docgenerator) for more details. You can [browse the new docs here](https://w3c.github.io/mnx/docs/).

Remaining to-dos are:

* Migrate all stable parts of the spec into the doc system. This involves creating "XML Elements" in the DB, adding their attributes/relationships/datatypes and adding descriptions.
* Figure out what to do with the MusicXML examples of "MNX By Example." All MNX examples from that older document have already been migrated into the new system; only the MusicXML examples and the short textual description of each example remain.
* Improve the new docs system to deal with "complex types." This is especially crucial in order to be able to support MusicXML.
* Improve the docs design. I'm planning to ask a colleague to help with this.
* Improve the new docs system to support one-off HTML pages, such as tutorials.
* Improve the new docs system to generate XSD from its database.

**Comment by cecilios** [comment]
@adrianholovaty Thanks for working on this. Regarding the MusicXML examples on the previous page "MNX By Example", they were very illustrative and useful to compare and assess the changes. I would vote to keep them on the new pages when convenient, side by side as they were on the old pages, if it is possible and their maintenance does not require excessive work.

**Comment by adrianholovaty** [comment]
@cecilios Thanks for the thoughts. Yes, I agree the comparisons with MusicXML are very useful!

**Comment by notator** [comment]
Here's my TODO list for the old (readonly)  _MNX by Example_ examples:
1. There are 10 examples that need to be updated to use a '#' character at the start of each reference to a local ID.
2. The 5 _Repeat_ examples need versions containing temporal information (`<actions>`, `<goto>` etc.) as in the Jumps examples I just posted (#218, #220, #221). One of them also needs  `<text>`. But all those elements need to be publicly discussed/improved/approved before I continue. (see #214, #215)

**Comment by notator** [comment]
@adrianholovaty Your first TODO says
> Migrate all stable parts of the spec into the doc system.

Merging PR #213 into the master branch now would stabilize the spec, and probably save some future work.

**Comment by adrianholovaty** [comment]
Status update: As of 028c8b9, the new docs system now has a [Comparing MNX and MusicXML page](https://w3c.github.io/mnx/docs/comparisons/musicxml/), which is essentially a replacement for the [old MNX By Example page](https://w3c.github.io/mnx/by-example/).

The new page has some new features:

* In the MNX examples, each element and attribute is linked to the appropriate docs page.
* Each example document ([see list](https://w3c.github.io/mnx/docs/examples/)) now deep-links to the appropriate part of the "Comparing MNX and MusicXML page" if the latter page contains that example.

It may be slightly confusing for each example to live in two places ("Comparing MNX and MusicXML" plus the examples section), but I think there's benefit in having all of the MusicXML comparisons on a single page, for easy, tutorial-style consumption by somebody new to MNX. I expect we'll tweak the way this works at some point, especially as the number of examples grows.

Remaining todos for this line of work:

* Add a way to specify the ordering of the examples on /comparisons/musicxml/. At the moment ordering is undefined.
* Implement the 'Show relevant section' vs 'Show full document'.

Once those last todos are done, I'll remove the old MNX By Example page and redirect it to the new page.

**Comment by adrianholovaty** [comment]
Status update: As of 8a02d351, the new docs system's [Comparing MNX and MusicXML page](https://w3c.github.io/mnx/docs/comparisons/musicxml/) now has the "Show relevant section" vs. "Show full document" logic. This is created dynamically; the system looks for a magic `<metadiff>` element within the examples to know which sections should be treated as "relevant." See the commit message for technical details.

Just one thing remaining before I can redirect the old By Example page to this new page: adding a way to specify ordering of the examples.

**Comment by samuelbradshaw** [comment]
This is really cool. Nice work!

**Comment by notator** [comment]
The following examples are either missing from [the above list](https://w3c.github.io/mnx/docs/examples/) or need to be updated:
- Beamed grace notes (#224)
- Mid-measure repeats (#222)
- Grand Staff with cross-staff beams (#219)
- Jumps1 (dal segno) (#221)
- Jumps2 (dal segno al fine) (#220 )
- Jumps3 (dal segno al coda) (#218)

As per my TODO list above, I have now created a new example showing how to group parts. According to this example, _all_ the MNX examples need to be updated. See https://github.com/w3c/mnx/issues/185#issuecomment-780403076.

**Comment by adrianholovaty** [comment]
Status update: As of 7cbab6813, "MNX By Example" has been fully replaced by the (essentially identical) version in the new docs system. See the commit message for more details. The old URL has been redirected to the new one.

**Comment by adrianholovaty** [comment]
This work was done a little while ago (see also #253).
