### ISSUE TITLE
MNX by Example: Beams (with inner grace note)

### ISSUE THREAD

**Issue by notator** [w3c/mnx#225]
This is an edit of [the existing "Beams (with inner grace notes)" example](https://w3c.github.io/mnx/by-example/#beamgrace) that
1.  _includes_ the grace note encoding.
2. includes a '#' character at the start of each reference to a local ID.
3. reduces the height of the screenshot staff to that of the other examples in this series.

![beamAroundGraceNote](https://user-images.githubusercontent.com/1655500/105350540-a21a3200-5beb-11eb-9e43-716088dd5b92.png)

```
<mnx>
    <global>
        <measure>
            <directions>
                <time signature="4/4"/>
            </directions>
        </measure>
    </global>
    <part>
        <part-name>Music</part-name>
        <measure>
            <directions>
                <clef line="2" sign="G"/>
            </directions>
            <sequence>
                <beams>
                    <beam events="#ev1 #ev3 #ev4 #ev5"/>
                </beams>
                <event id="ev1" value="/8">
                    <note pitch="C5"/>
                </event>
                <grace>                
                    <event value="/8">
                        <note pitch="B4"/>
                    </event>
                </grace>
                <event id="ev3" value="/8">
                    <note pitch="D5"/>
                </event>
                <event id="ev4" value="/8">
                    <note pitch="E5"/>
                </event>
                <event id="ev5" value="/8">
                    <note pitch="F5"/>
                </event>
                <event value="/2">
                    <rest/>
                </event>
            </sequence>
        </measure>
    </part>
</mnx>
```

**Comment by adrianholovaty** [comment]
Thanks @notator. I've updated the new docs in commit 1a903cc5. This involved adding `<grace>` to the new docs system and updating the "Beams (with inner grace note)" example to use `<grace>` properly.

I didn't update the image, as I don't think we should endeavor to make every screenshot image have the same height. In practice that's not going to be feasible given the wealth of examples we'll have — so I don't want to set the expectation that we'll be doing that. We can always set screenshots' width and height via CSS in the docs.

Regarding your change to add "#" to the ID list — could you remind me of why you're suggesting that?

**Comment by notator** [comment]
The discussion on hash tags begins with a comment from @ahankinson at https://github.com/w3c/mnx/pull/190#issuecomment-748117620. :-)

**Comment by adrianholovaty** [comment]
Thanks. I don't see a good reason to add/require those hash marks. It makes the parsing slightly more annoying for developers and doesn't offer any strong benefit.

Marking this pull request as closed, now that the docs have been updated.
