### ISSUE TITLE
<part-name> element feels inconsistent with rest of MNX schema

### ISSUE THREAD

**Issue by mnquintana** [w3c/mnx#227]
From https://w3c.github.io/mnx/docs/comparisons/musicxml/#hello-world:

```xml
<mnx>
    ...
   <part>
      <part-name>
         Music
      </part-name>
      <measure barline="regular">
         <directions>
            <clef sign="G" line="2"/>
         </directions>
         <sequence>
            <event value="/1">
               <note pitch="C4"/>
            </event>
         </sequence>
      </measure>
   </part>
</mnx>
```

[Given MNX's emphasis on attributes over child nodes](https://w3c.github.io/mnx/specification/common/#design-notes) for properties that only ever belong to one element, it feels inconsistent with the rest of the spec that `<part-name>` is a separate element for defining a part name.

## Expected

```xml
<part name="Music">
    ...
</part>
```

## Actual

```xml
<part>
    <part-name>Music</part-name>
    ...
</part>
```

## Proposal
1. Remove the `<part-name>` element
2. Replace it with a `name` attribute on the `<part>` element

What do y'all think?

**Comment by notator** [comment]
I think the examples currently in  [Comparing MNX and MusicXML](https://w3c.github.io/mnx/docs/comparisons/musicxml/) have to be thought of as placeholders. They have to be subject to revision as MNX develops.

As I said in https://github.com/w3c/mnx/issues/185#issuecomment-780403076, under the heading **Naming**
> The `<part><part-name>` element has [...] been deleted [...]. If the part has a printed name of any kind, it is found via a reference to the part's [optional] `<instrumentType>`.

My current version of _hello world_  simply omits the part's name since it is not needed for the example.

**Comment by adrianholovaty** [comment]
Thanks @mnquintana — I like this suggestion and think it makes a lot of sense at first glance.

Thinking through any potential downsides, they could be...

1. It means part names couldn't have newlines. [seems an OK limitation]

2. It means part names couldn't have any child elements, such as formatting a subset of the name in bold/italic (a contrived example). [seems an OK limitation]

3. It means the `name` attribute would need to be able to handle part names that contain special characters — most commonly, accidentals. MusicXML handles this with `<accidental-text>` (see example at bottom of [this page](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-accidental-text.htm)). I think it would be OK to require people to simply use the proper Unicode character for sharp/flat/natural, but there might be some edge cases I'm overlooking here.

4. It means it would be trickier (and less elegant) to add additional metadata to the part name. The nice thing about having a dedicated `<part-name>` element is that it provides a natural place for metadata, via attributes. Off the top of my head, some potentially useful metadata would be:

* A "full name" vs. "short name." Some notation apps use a full name for the first system (and in their UI) but an abbreviated version on subsequent systems. MusicXML handles this via `<part-name-display>` and `<part-abbreviation-display>`, and MNX should have a solution as well. If we go with attributes, I don't think `<part name="Bb trumpet" name-short="Trpt.">` is a bad solution, though.

* A way to disable rendering (the equivalent of MusicXML's `print-object` attribute). Perhaps `<part-name shown="false">` would be useful to specify that the part name shouldn't be rendered. Then again, perhaps that's too presentational and belongs in a separate styling/presentation part of the document (which is very hand-wavy and yet undesigned).

Of all of the above, only the fourth gives me any kind of real pause. Do people see any other downsides to making this change?

**Comment by samuelbradshaw** [comment]
> * A "full name" vs. "short name." Some notation apps use a full name for the first system (and in their UI) but an abbreviated version on subsequent systems. MusicXML handles this via `<part-name-display>` and `<part-abbreviation-display>`, and MNX should have a solution as well. If we go with attributes, I don't think `<part name="Bb trumpet" name-short="Trpt.">` is a bad solution, though.
Alternatively, `<part name="B♭ trumpet" abbreviation="Trpt.">`

**Comment by adrianholovaty** [comment]
@samuelbradshaw Ah, yes, that is cleaner. :) Thanks!

**Comment by mdgood** [comment]
I think the lack of newlines will make this change impractical. Plenty of parts have line breaks within their names, especially percussion parts. When you need to preserve whitespace exactly, you have to use element content rather than attribute content.

**Comment by ahankinson** [comment]
Note that not all generic XML parsers preserve newlines (e.g., if a standard XML formatter is run on the file, it is perfectly within the spec to remove any newlines). The solution is generally to specify the contents of the tag in `CDATA`, or to build in tags that introduce newlines when processed (e.g., `<br>` or `<lb>`).

**Comment by mdgood** [comment]
In cases like this where preserving white space can be important, elements should declare the `xml:space` attribute to signal how the application should handle white space. As the [white space handling section of the XML spec](https://www.w3.org/TR/xml/#sec-white-space) states:

> The value "default" signals that applications' default white-space processing modes are acceptable for this element; the value "preserve" indicates the intent that applications preserve all the white space.

MusicXML does this with the `<display-text>` element and any element that uses the `text-formatting` attribute group. Hopefully MNX can support this without the need for separate `<part-name>` and `<part-name-display>` elements. 

I don't think we need to worry about parsers or applications that don't handle the `xml:space` attribute. To the best of my knowledge it hasn't been a practical problem in our MusicXML work.

**Comment by evanlenz** [comment]
Yes, an XML parser is not allowed to strip newlines from element content.
It only normalizes them in attribute values. Otherwise, it’s not an XML
parser. That’s true regardless of how it’s represented (literal character,
CDATA section, character reference, etc.)

**Comment by samuelbradshaw** [comment]
```
      <part-name>
         Part
         Name
      </part-name>
```

Preserving all whitespace can also cause problems. For example, in the snippet above, you might want the new line at the end of line 2, but you probably wouldn't want the new line at the end of lines 1 or 3, or the spaces at the beginning of lines 2 and 3. If all white space is preserved by default, but you only wanted the new line after "Part," you would have to write the above snippet like this:

```
      <part-name>Part
Name</part-name>
```

**Comment by adrianholovaty** [comment]
@mdgood wrote:
> I think the lack of newlines will make this change impractical. Plenty of parts have line breaks within their names, especially percussion parts. 

Interesting — could you expand on this? Are those line breaks purely presentational? And do you think there could be a way of addressing the presentational aspect while enabling a non-line-breaked part name? Also, I'm curious to see some percussion part examples if you have 'em.

I think there could be some benefit to requiring part names not to have whitespace; it just feels cleaner and more semantic. As long as we provide a way for people to encode their preferred line breaks (assuming line breaks are only for presentational purposes).

**Comment by mdgood** [comment]
There are indeed tradeoffs between the semantics and the presentation - and how both can differ between score and parts, too.

Here are a couple of examples. They don't capture quite the example I initially had in mind (and couldn't find quickly), but they have other things just as good: 1) doubling instruments combined in the Holst - on one line if they fit, but separated one instrument per line if they don't; 2) semantics of the part name split up presentationally between what in MusicXML would be the part name and the group name, plus more doublings on two lines.

In MusicXML this is split into the semantic part-name element and the presentational part-name-display element. It is nice if MNX can unify these things but of course sometimes that may not turn out to be the best approach.

Holst:
![Holst Parts Page 1](https://user-images.githubusercontent.com/11082681/109886637-3d63e580-7c35-11eb-96f9-c266ccee63bd.png)

Schoenberg:
![Schoenberg Parts Page 1](https://user-images.githubusercontent.com/11082681/109887208-2b367700-7c36-11eb-82b7-47b5317ae135.png)

**Comment by bhamblok** [comment]
Besides the issue of new lines discussed here above, I also would like to add another argument to keep this element `<part-name>` in place:

If we define "content that needs to be visualised" as a value of an attribute, we lose a one to one mapping of "visual elements" with "digital elements" in our data-structure.

**Comment by notator** [comment]
If we use HTML entities (as was found useful in #190), names (or name components) can be described in a single line.
For example: `"Trumpet&nbsp;in&nbsp;B&flat;"` translates (here too!) to "Trumpet&nbsp;in&nbsp;B&flat;".
Applications could easily display such a string on two or more lines in cramped space if they needed to.

As a result of working on #185, I think the naming of instruments should be encapsulated in a global `<instrumentType>` element that is referenced from each `<part>`, as demonstrated in [my partGroups draft](https://github.com/notator/mnx/blob/main/mnx-examples/common1900/graphicsOnly/parts-voices-staves/partGroups.mnx).
Its not always necessary to print the full name of an instrument, so the `<instrumentType>` could be extended to include a `longName` attribute:
`<instrumentType id="trumpet" groupName="trumpets" name="Trumpet" longName="Trumpet&nbsp;in&nbsp;B&flat;" nameAbbrev="Tp." />`

**Comment by adrianholovaty** [comment]
As of 0d5cabb14, the `<part>` element has `name` and `short-name` attributes, and the new "layouts" system provides ways of overriding the rendered part name. It also provides a solution for stacking names together on the same staff, hence removing the need for the line-breaks-in-part-names hack. The layouts system is also a clear place to do any further expansion of part-name formatting in the future.

With that in mind, I've cleaned things up and removed the `<part-name>` element in d471cba.
