### ISSUE TITLE
Add syntax highlighting to MNX examples

### ISSUE THREAD

**Issue by mnquintana** [w3c/mnx#229]
## Proposal

I think it would go a long way to making the MNX by example page a bit more readable if both the MNX and MusicXML examples had syntax highlighting, hopefully making it easier to grok the core semantics too.

We wouldn't need to reinvent the wheel or anything here – reusing regular ol' XML language grammars for syntax highlighting should be good enough, we don't need to create a custom one for MusicXML and MNX.

We could use something like [Prism.js](https://github.com/PrismJS/prism) or [highlight.js](https://github.com/highlightjs/highlight.js) for adding syntax highlighting support (they're both pretty battle-tested for this exactly kind of use case – syntax highlighting in developer docs).

### Without syntax highlighting

```
<mnx>
   <global>
      <measure>
         <directions>
            <time signature="4/4"/>
         </directions>
      </measure>
      <measure/>
   </global>
   <part>
      <part-name>Music</part-name>
      <measure>
         <directions>
            <clef sign="G" line="2"/>
         </directions>
         <sequence>
            <event value="/4">
               <note pitch="C4"/>
            </event>
            <event value="/4">
               <note pitch="D4"/>
            </event>
            <event value="/4">
               <note pitch="E4"/>
            </event>
            <event value="/4">
               <note pitch="F4"/>
            </event>
         </sequence>
      </measure>
      <measure barline="regular">
         <sequence>
            <event value="/4">
               <note pitch="G4"/>
            </event>
            <event value="/4">
               <note pitch="A4"/>
            </event>
            <event value="/4">
               <note pitch="B4"/>
            </event>
            <event value="/4">
               <note pitch="C5"/>
            </event>
         </sequence>
      </measure>
   </part>
</mnx>
```

### With syntax highlighting

(This is just the standard XML language syntax highlighting)

```xml
<mnx>
   <global>
      <measure>
         <directions>
            <time signature="4/4"/>
         </directions>
      </measure>
      <measure/>
   </global>
   <part>
      <part-name>Music</part-name>
      <measure>
         <directions>
            <clef sign="G" line="2"/>
         </directions>
         <sequence>
            <event value="/4">
               <note pitch="C4"/>
            </event>
            <event value="/4">
               <note pitch="D4"/>
            </event>
            <event value="/4">
               <note pitch="E4"/>
            </event>
            <event value="/4">
               <note pitch="F4"/>
            </event>
         </sequence>
      </measure>
      <measure barline="regular">
         <sequence>
            <event value="/4">
               <note pitch="G4"/>
            </event>
            <event value="/4">
               <note pitch="A4"/>
            </event>
            <event value="/4">
               <note pitch="B4"/>
            </event>
            <event value="/4">
               <note pitch="C5"/>
            </event>
         </sequence>
      </measure>
   </part>
</mnx>
```

**Comment by adrianholovaty** [comment]
Good news — the building blocks are already in place for this. The docs system formats the markup examples one XML element at a time, and it would be easy to insert some HTML hooks for fine-grained styling.

See the file `docgenerator/spec/utils/htmlutils.py` in the mnx repo, specifically the `XMLAugmenter` class. We're already adding `class="tag"`, `class="attr"` and `class="xmltxt"` for element names, attributes and element text respectively. We could additionally add a CSS class around the angle brackets to style those differently.

**Comment by mnquintana** [comment]
Excellent! Would that generalize for syntax highlighting MusicXML too? Or is it specific to MNX right now?

**Comment by mdgood** [comment]
@mnquintana The plan is to use the same software, including syntax highlighting, for both the MusicXML and MNX specs. @adrianholovaty gave @dspreadbury and me a demo of the progress on supporting the MusicXML spec today. It is very exciting to see this come together!

**Comment by adrianholovaty** [comment]
I've just implemented syntax highlighting in the MNX documentation. You can see it in action on [any example page](https://w3c.github.io/mnx/docs/mnx-reference/examples/) or in the ["Comparing MNX and MusicXML" page](https://w3c.github.io/mnx/docs/comparisons/musicxml/).

I used the same colors from your screenshot, though these are easy to change via CSS.

Thanks for the suggestion!
