### ISSUE TITLE
Consider changing the name of our primary branch from `master` to `main`

### ISSUE THREAD

**Issue by ericcarraway** [w3c/mnx#233]
Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`.

- On GitHub, `main` has been the default branch name for new repositories since October 2020.
- GitLab has a release planned for this month which will do the same.
- Most repositories in the W3 organization use `main`

<details>

850 W3C Repositories on 2021-04-20

| Name            | Count |
| --------------- | -----:|
| `main`          |   271 |
| `master`        |   266 |
| `gh-pages`      |   191 |
| other           |     4 |
| archived status |   118 |

</details>

**Comment by adrianholovaty** [comment]
Thanks for making this suggestion. I've just made the change. Apparently it temporarily broke our GitHub Pages installation, but I believe that's being worked out as caches get cleared.
