### ISSUE TITLE
Transposing Instruments in Conductor Scores

### ISSUE THREAD

**Issue by clnoel** [w3c/mnx#250]
We need a way of specifying a transposing instrument so that we can create both a transposed, single-instrument score and a concert-pitch conductor score.

Note: The problems with transposing instruments and respelling got hashed and rehashed in #34 and #4 and I've got to admit that I am heartily sick of dealing with the differing points of view, even thought I know that this is an important topic. One thing I am absolutely opposed to is having two <part> tags for the same part because it happens to be a transposing instrument. I feel like that is just a bad idea, but I don't have a better idea right now.

This was originally listed in https://github.com/w3c/mnx/issues/185#issuecomment-948018127 as in-scope topic (7), but has since been removed as out-of-scope.

**Comment by adrianholovaty** [comment]
Marking this closed in favor of #287.
