### ISSUE TITLE
Remove "target" attribute in <tied>?

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#257]
This proposal comes from @notator in #203. I'm splitting it into a separate issue to better organize things.

> The `<tied>` `target="noteID"` attribute is redundant and should simply be omitted. The target note must _always_ be in the following `<event>` in the voice, and have the same pitch as the original tied `<note>`, so we don't need the ID.

**Comment by adrianholovaty** [comment]
My own two cents: I understand how this can be seen as redundant, but I don't think the change is worth making, for these reasons:

1. Using IDs is very practical and useful. Much faster to simply do an ID lookup than to traverse the notation data structure.
2. The proposal fails in the case of the next `<event>` having two `<note>`s with the same pitch. Which of the `<note>`s would get the tie?
3. The proposal fails in the case of the next `<event>` being in a separate measure that contains multiple sequences (multiple "voices," though MNX doesn't have the concept of voices). Which of the sequences should get the tie? You could argue "use the same sequence index as the note that starts the tie," but that's a bit brittle and MNX currently doesn't require that a "voice" be put in the same sequence index across measures. (Anybody who disagrees with this should feel free to open a separate issue rather than discussing here...)

**Comment by joeberkovitz** [comment]
Following up on @adrianholovaty's comment above (which I agree with), in the literature there are lots of notated ties which do not go to a following event in the same voice. Polyphonic keyboard music sometimes will tie a note in one voice to a later note in a different voice. Often this occurs when a homophonic part was notated as a single voice splits into polyphony in a subsequent. Note the tied A across the two bars below, from a piano reduction of John Dowland's _Lachrymae Coactae_:

![image](https://user-images.githubusercontent.com/165916/140811800-874bf3fd-5d90-4b9e-bf04-41be70c7066c.png)

It is also not the case that voice assignments can always be juggled to prevent the above from happening — and we should never mandate such assignments anyway.

**Comment by clnoel** [comment]
I understand the issue, I agree that we should have a target. It makes it a lot less work, and makes it a lot less likely that we'll end up unable to find the other end of the tie, which happens to us rather frequently in MusicXML from some sources.

P.S. I disagree that we can't encode the example with coherent voices. I see a piece with three voices in the top staff, two voices in the bottom staff, and two stemming layouts. (One where the two top-staff downstem voices are stemmed together, and one where they are stemmed slightly offset from one another.) I would love to see a case that really couldn't be split that way. I think it would be an interesting challenge (if totally off-topic) to encode a piano reduction from the original parts by just defining the layouts. Hmm...

**Comment by joeberkovitz** [comment]
@clnoel true, but we could tweak it so that approach doesn't work by getting rid of the 3rd voice in the treble staff—just delete the opening E4 dotted whole note.

I secretly love your idea of reductions as layouts though... let's come back to that.

**Comment by notator** [comment]
I also now agree with everyone that the target ID should be kept. As @joeberkovitz says:
>Polyphonic keyboard music sometimes will tie a note in one voice to a later note in a different voice.

Its sometimes useful, for discussion purposes, to consider where the naive approach goes wrong! :-)

**Comment by adrianholovaty** [comment]
All right, in that case I'm marking this one as closed.
