### ISSUE TITLE
Tuplets and augmentation dots become annotations in the presence of explicit timing data

### ISSUE THREAD

**Issue by notator** [w3c/mnx#26]
I raised this issue at the recent face-to-face meeting in Frankfurt (see the Minutes) using the Fauré example, but it needs to be resolved here so that we can begin to think of defining the GMNX format more precisely.

Issue #23 has established that GMNX is intended to include performance (i.e. explicit timing) information. This is a fundamental change from the situation in MusicXML.
MusicXML was designed for sheet music, in which timing information is calculated from metronome marks, tuplet brackets and augmentation dots _in the graphics_. Since there is only one set of graphics, that approach can only describe one (default) performance.

If the durations of event symbols are provided explicitly in a score (e.g. as a number of milliseconds), then the score can easily be played back by a machine without having to calculate the durations by looking at the graphics. The graphics still have an important function (they make the score easier for humans to read), but they can be ignored by a performing application.
So, in GMNX, metronome marks, tuplets and augmentation dots have to be regarded simply as the annotations used in current CWMN. 

Note that the durations of "tuplet" eighths in a quarter, neither have to be exactly equal to each other, nor do they have to be exactly equal to values calculated from a metronome mark. That's especially important when it comes to synchronizing the score with one or more real performances.
Similarly, augmentation dots don't have to lead to precisely calculatable durations. That's important, for example, in French Baroque music...
Programs designed to play back Viennese Waltzes would also benefit from this approach, even if they use neither tuplets nor augmentation dots.

**Comment by joeberkovitz** [comment]
GMNX doesn't have any concept of metronome marks, tuplets or augmentation dots, nor of any other CWMN-like constructs. GMNX just provides some arbitrary graphics, and a set of timed events (expressed in seconds). If there is a tuplet or a dot in the score, these are just shapes that occur somewhere in the graphics, which may be correlated with a timed event.

Also, GMNX allows multiple performances to be associated with the same score.

So as far as I can tell, there is no issue here.

**Comment by mdgood** [comment]
I agree with Joe that there is no GMNX issue here. I did want to add that MusicXML includes both a `<sound>` element and many attributes such as "attack" and "release" that can specify a specific performance beyond what is specified in score graphics.

**Comment by notator** [comment]
@joeberkovitz and @mdgood I think we agree that GMNX scores must allow multiple performances of a score to be stored in the same file, but that MusicXML does not do that. Presumably, CWMNX will also just contain the information for a single performance.

This issue has to do with the detailed structure of a GMNX score, and how it treats the embedding of temporal information inside event symbols. Music notations are characterized by their having event symbols, so I think such symbols should be a basic construct in the format (Issue #25). Augmentation dots are, for example, event symbol _components_, so they will never need to be associated directly with a position in time.

This issue (#26) is just to ensure that we all understand that there is no conflict even when event symbols are the basic unit of synchronization, and that GMNX scores (as defined in both the [MNX Proposal Overview 26th April 2017](https://w3c.github.io/mnx/overview/) and in Issue #25) can perfectly well contain scores written in CWMN.

I think we should postpone further debate on Issue #25 until the MNX Proposal Overview has been clarified (Issue #23).

**Comment by joeberkovitz** [comment]
After reading @notator's reply I continue to agree with @mdgood that there's no issue here.

The proposal is pretty clear that CWMNX _by default_ calculates durations using standard meanings for note values. However, it can be overridden to _explicitly_ specify playback durations using explicit timings, in terms of a prevailing tempo. This is explained in https://w3c.github.io/mnx/overview/#interpretation and where such overrides occur.

CWMNX has the purpose of capturing a single set of performance instructions, which is appropriate for some given edition of a CWMN score (although not for arbitrary notational idioms). GMNX is where multiple (and exact) performances can be captured. In that realm, I'll restate that dots and symbols as such don't exist except as graphics.

So I think we have clarified these points already and the specification will make this even clearer.

If there are further issues, please file suggestions for specific changes to the proposal. Right now this issue continues to feel vague and lacks a statement of what should be changed and why.

**Comment by joeberkovitz** [comment]
For clarity, here's a worked example. Note that the SVG is relieved of any need to classify graphics as tuplets, notes, or dots. Nor does it have to be concerned about nesting note graphics inside tuplet graphics to show the relationship, or associating dot graphics with note graphics -- these relationships are encoded entirely by the CWMNX score to which the SVG refers,.

GMNX performance content for, say, a dotted note in a tuplet would contain these elements (crudely):

```xml
<performance>
   ...
    <event graphic="#note1" start="5.232" duration="0.25">
        <note pitch="E4" dynamics="100"/>
     </event>
   ...
</performance>
```

GMNX graphics content would contain this:
```xml
<svg>
  ...
  <g id="note1" mnx:semantics="score.cwmnx#note1">
    ...graphics for the note
  </g>
</svg>
```

And `score.cwmnx` would contain:

```xml
<score>
   ...containing parts, measures, sequences omitted...
   <tuplet actual="3/8" normal="2/8">
       <event value="4*">
          <note id="note1" pitch="E4"/>
       </event>
   </tuplet>
</score>
```

**Comment by notator** [comment]
@joeberkovitz 

CWMNX
> If there are further issues, please file suggestions for specific changes to the proposal.

Done: see issue #27.

I've filed a new issue (#28) about SVG `class` attributes.

**Comment by joeberkovitz** [comment]
This issue doesn't appear to have any content that is not already broken out into #27 (absolute timing in CWMNX) and #28 (use of `class` to semantically label SVG graphics). So it's likely to be closed at the next review.

**Comment by joeberkovitz** [comment]
Closing this issue due to lack of any concrete implications for the markup.

Please contact chairs directly before posting further on this thread.
