### ISSUE TITLE
Add support for multi-bar rests

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#284]
Here are a few proposals for how MNX can handle multi-bar rests. As you'll see, there are some open questions around where this data should live and how much flexibility MNX should provide.

We'll use the following music in each example. It consists of a full score, plus two individual parts:
![mnx_score_parts](https://user-images.githubusercontent.com/180401/177207561-f077ac71-f382-4ae0-b356-e6f0651f1c16.png)

Some things to note, before I get into proposals:

* The two parts each have multi-bar rests. Part A has one, and Part B has two.
* Multi-bar rests are only rendered in the individual parts, not in the full score. The full score simply uses "normal" whole rests for those bars.
* To be precise about terminology: I'm using the word "part" to mean the rendered music notation as typically distributed to musicians playing a specific instrument and in contrast with the "full score." I'm using the syntax-highlighted term `<part>` when referring to the contents of the MNX `<part>` element (which contains the semantic notation data for a given instrument and is in turn used when generating the full score and parts).
* In chatting about this with my fellow co-chairs, we agreed that a rules-based approach is off the table. It's tempting to encode something like "In this part, find any contiguous sections of at least two empty measures, and automatically convert those into multi-bar rests" — but we need to handle multiple multi-bar rests next to one another (deliberately split into multiple multi-bar rests to communicate musical structure or time/key signature changes, etc). So we need to be explicit about the multi-bar rest locations rather than encoding implicit rules.

Here is the basic MNX document for this notation data, excluding any multi-bar rest information:

```xml
<mnx>
  <global>
    <measure-global>
      <directions-global>
        <time signature="4/4"/>
      </directions-global>
    </measure-global>
    <measure-global/>
    <measure-global/>
    <measure-global/>
    <measure-global/>
    <measure-global/>
    <measure-global/>
  </global>
  <part id="PartA">
    <measure>
      <directions-part>
        <clef sign="G" line="2"/>
      </directions-part>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <note pitch="E5"/>
        </event>
      </sequence>
    </measure>
  </part>
  <part id="PartB">
    <measure>
      <directions-part>
        <clef sign="G" line="2"/>
      </directions-part>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/4">
          <note pitch="D5"/>
        </event>
        <event value="/2">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/4">
          <note pitch="D5"/>
        </event>
        <event value="/2">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
  </part>
  <score name="Full score">
    <page>
      <system measure="1"></system>
      <system measure="5"></system>
    </page>
  </score>
  <score name="Part A">
    <page>
      <system measure="1"></system>
    </page>
  </score>
  <score name="Part B">
    <page>
      <system measure="1"></system>
    </page>
  </score>
</mnx>
```

Note that there are three `<score>` elements to represent the three different views of the music — "Full score", "Part A" and "Part B".

With that preamble out of the way, here are the proposals...

## 1. Put multi-bar rests in `<part-layout>`

Here, we invent a `<multibar-rest>` element, as a child of the existing `<part-layout>` element ([see here](https://w3c.github.io/mnx/docs/mnx-reference/elements/part-layout/)). This puts the multi-bar rest information solely within our existing [layouts system](https://w3c.github.io/mnx/docs/mnx-reference/examples/multiple-layouts/).

```xml
  <layouts>
    <system-layout id="PartALayout">
      <staff-layout>
        <part-layout part="PartA">
          <multibar-rest measure="3" length="2" />
        </part-layout>
      </staff-layout>
    </system-layout>
    <system-layout id="PartBLayout">
      <staff-layout>
        <part-layout part="PartB">
          <multibar-rest measure="1" length="2" />
          <multibar-rest measure="5" length="2" />
        </part-layout>
      </staff-layout>
    </system-layout>
  </layouts>
  <score name="Full score">
    <page>
      <system measure="1"></system>
      <system measure="5"></system>
    </page>
  </score>
  <score name="Part A">
    <page>
      <system measure="1" layout="PartALayout"></system>
    </page>
  </score>
  <score name="Part B">
    <page>
      <system measure="1" layout="PartBLayout"></system>
    </page>
  </score>
```

Using the power and flexibility of our layouts system means that you can create any kind of multi-bar rest you want for any `<part>`, and the data is all nicely contained in the `<layouts>` section of the document.

The downside is the complexity and verbosity. Any multi-bar rest would effectively need its own `<system-layout>`, which would get verbose quickly and would go against the spirit of making layouts reusable.

## 2. Put multi-bar rests in `<system>`

With that in mind, could we put the multi-bar rest data within `<score>` in a way that doesn't require us to use a layout?

In this second proposal, we invent two elements, `<system-part>` and `<multibar-rest>`. The idea is that `<system-part>` contains _semantic_ data about a specific `<part>` in a specific `<system>`; this is distinct from _layout_ data.

```xml
  <score name="Full score">
    <page>
      <system measure="1"></system>
      <system measure="5"></system>
    </page>
  </score>
  <score name="Part A">
    <page>
      <system measure="1">
        <system-part part="PartA">
          <multibar-rest measure="3" length="2" />
        </system-part>
      </system>
    </page>
  </score>
  <score name="Part B">
    <page>
      <system measure="1">
        <system-part part="PartB">
          <multibar-rest measure="1" length="2" />
          <multibar-rest measure="5" length="2" />
        </system-part>
      </system>
    </page>
  </score>
```

With this approach, we don't need to create layouts simply for the purpose of encoding multi-bar rests. It also gives us a firm place to attach other part-specific information of this kind (though I can't think of any examples...).

The downside is that the concepts of "part-specific semantic data" and "part-specific layout data" are _very_ conceptually similar, to the point where it feels a bit obtuse to make a distinction. I could envision this being a point of confusion for MNX users: "Why is some of the information in `<system-part>` while other information is in `<part-layout>`?"

## 3. Put multi-bar rests in `<measure>`

What if we allowed ourselves to add multi-bar rest data directly within `<part>`? At first thought this might seem like it's mixing semantics with presentation, because `<part>` is intended to be "pure" semantic notation data — but the locations of multi-bar rests _are_ semantic.

Here, `<measure>` elements within `<part>` get a `multibar-rest` attribute, whose value is the length of the multi-bar rest that begins in that bar. By default, this data is ignored. But a `<part-layout>` can opt in to using this data via `multibar-rests="on"`.

```xml
  <part id="PartA">
    <measure>
      <directions-part>
        <clef sign="G" line="2"/>
      </directions-part>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure multibar-rest="2">
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <note pitch="E5"/>
        </event>
      </sequence>
    </measure>
  </part>
  <part id="PartB">
    <measure multibar-rest="2">
      <directions-part>
        <clef sign="G" line="2"/>
      </directions-part>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/4">
          <note pitch="D5"/>
        </event>
        <event value="/2">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/4">
          <note pitch="D5"/>
        </event>
        <event value="/2">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
    <measure multibar-rest="2">
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
  </part>
  <layouts>
    <system-layout id="PartALayout">
      <staff-layout>
        <part-layout part="PartA" multibar-rests="on" />
      </staff-layout>
    </system-layout>
    <system-layout id="PartBLayout">
      <staff-layout>
        <part-layout part="PartB" multibar-rests="on" />
      </staff-layout>
    </system-layout>
  </layouts>
  <score name="Full score">
    <page>
      <system measure="1"></system>
      <system measure="5"></system>
    </page>
  </score>
  <score name="Part A">
    <page>
      <system measure="1" layout="PartALayout"></system>
    </page>
  </score>
  <score name="Part B">
    <page>
      <system measure="1" layout="PartBLayout"></system>
    </page>
  </score>
```

This has a certain elegance (and I'm partial to it because the Soundslice data format works this way).

The downside is the lack of flexibility. For each `<part>`, there can only be _one_ arrangement of multi-bar rests. So it would be impossible to create multiple `<score>`s with each having different locations of multi-bar rests for the same `<part>`.

Is this a dealbreaker? How common is it for the same underlying notation data to have _different configurations of multi-bar rests_ in different contexts? I have the feeling that's a rare situation, but I'd like to get feedback from people in the trenches.

## 4. Put multi-bar rests in `<measure>` but make them addressable

Here's an attempt to solve idea 3's lack of flexibility. Instead of a boolean "multi-bar rests are either available or not for this particular `<measure>`", a multi-bar rest is given a `class` attribute. Then a layout can "opt into" any multi-bar rests of a certain class.

```xml
  <part id="PartA">
    <measure>
      <directions-part>
        <clef sign="G" line="2"/>
      </directions-part>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <multibar-rest length="2" class="multibars" />
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="C5"/>
        </event>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/2">
          <note pitch="G5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <note pitch="E5"/>
        </event>
      </sequence>
    </measure>
  </part>
  <part id="PartB">
    <measure>
      <multibar-rest length="2" class="multibars" />
      <directions-part>
        <clef sign="G" line="2"/>
      </directions-part>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/4">
          <note pitch="D5"/>
        </event>
        <event value="/2">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/4">
          <note pitch="E5"/>
        </event>
        <event value="/4">
          <note pitch="D5"/>
        </event>
        <event value="/2">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
    <measure>
      <multibar-rest length="2" class="multibars" />
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <rest/>
        </event>
      </sequence>
    </measure>
    <measure>
      <sequence>
        <event value="/1">
          <note pitch="C5"/>
        </event>
      </sequence>
    </measure>
  </part>
  <layouts>
    <system-layout id="PartALayout">
      <staff-layout>
        <part-layout part="PartA" multibar-rest-selector=".multibars" />
      </staff-layout>
    </system-layout>
    <system-layout id="PartBLayout">
      <staff-layout>
        <part-layout part="PartB" multibar-rest-selector=".multibars" />
      </staff-layout>
    </system-layout>
  </layouts>
  <score name="Full score">
    <page>
      <system measure="1"></system>
      <system measure="5"></system>
    </page>
  </score>
  <score name="Part A">
    <page>
      <system measure="1" layout="PartALayout"></system>
    </page>
  </score>
  <score name="Part B">
    <page>
      <system measure="1" layout="PartBLayout"></system>
    </page>
  </score>
```

This feels a bit harebrained to me to be honest, but I'm just exploring the problem space. Perhaps there's something here worth salvaging.

## Concluding questions

Do any of these ideas resonate with you? Other proposals are also welcome!

And I'm especially interested in people's answers to the question I posed in idea 3. Is it good enough to limit each `<part>` to a specific set of multi-bar rest locations, or do we need to offer more flexibility?

Finally, if any developers of music-notation software want to share the details of their data model for multi-bar rests — what's worked and hasn't worked — that would be very valuable.

**Comment by adrianholovaty** [comment]
Related: See #121 for prior discussion on multi-bar rests, and see #34 for the larger/meta issue about differences between scores and parts.

**Comment by dspreadbury** [comment]
Following our discussion in our co-chairs' meeting today, a few thoughts from me:

My preference of these four proposals would be for option 1. Option 2 is a little redundant (there's no particular reason to tie the multi-bar rests to a system specifically, since it seems fine to encode them based on their starting bar number and the number of bars included within, which really has no relevance either to the system or to the page).

Options 3 and 4 feel wrong to me because multi-bar rests by their nature have to take into consideration the totality of the instruments/staves that are visible in the layout. Consider the case that you want to show a part layout for, say, violins 1 and 2 together (commonly done in film/commercial music so that the conductor can make balance changes on the fly from the stand). If the multi-bar rests for voilin 1 and 2 are encoded in `<measure>`, the consuming app has to parse out the multi-bar rests from the sequences for both parts, and work out where they can actually appear – it might be that the multi-bar rests in each part don't overlap at all, in which case none of them can be used, or that they partially overlap, in which case you would technically need to be able to split the encoded multi-bar rests into segments: only violin 1, only violin 2, and both violin 1 and 2.

So this feels wrong to me, since by encoding the information in the `<measure>` the consuming app can't actually just go ahead and follow the encoding to determine the correct appearance.

This, I think, means that the only practical approach is to encode multi-bar rests in layouts, since only layouts know which parts are going to be included, and can therefore encode the multi-bar rest ranges correctly.

I take slight issue with @clnoel's assertion that multi-bar rests are unambiguously at the level of staves. If you have a multi-staff instrument, such as a piano, you would never see a multi-bar rest in the right-hand staff but not in the left-hand staff, for example. And, indeed, as my example above where you have multiple instruments in the same layout demonstrates, they cannot even be correctly encoded at the level of an instrument (or part, in MNX parlance), because you may have multiple instruments in the same layout, and the multi-bar rests must take into account the music belonging to all of the instruments in the layout.

So I think it is in fact correct to say that multi-bar rests do live at the layout level, and that they apply to all staves in the layout, regardless of whether they belong to the same or different instruments. I would therefore propose that we follow option 1.

**Comment by clnoel** [comment]
Thus far, the `<layouts>` element has only contained _vertical_ information. That is, information that affects how many staves there are, how they are grouped,, and stemming information. On the other hand, `<score>` indicates _horizontal_ information, such as how many measures are in a system, (that is, how many will fit horizontally on a page).

It looks like I might be outvoted, but I strongly believe that a multibar rest is a piece of horizontal information that belongs in the `<score>`. 

@cecilios Parsers with no paging that care about how multiple parts combine on one stave (such as whether they are chorded or split-stem) at different times are still going to have to parse the page/system information in order to extract that information under our current spec, as this will be the most common usage of the `<system-layout-change>` element. Under 2A, `<multibar-rest>` is a sibling of that element.

**Comment by clnoel** [comment]
You know what, I could get behind that. Let's call it option 2B.

**Comment by adrianholovaty** [comment]
An update — @mdgood has suggested that we call the element `<multi-measure-rest>` given that we use the term `<measure>` in MNX (not bar).

**Comment by cecilios** [comment]
@adrianholovaty I agree with your proposed changes. Staff is not needed and I don't see the need to use measures locations as the whole measure is a rest. I copied the `<multibar-rest>` from another example without paying attention to its attributes. And also I agree with @mdgood proposal of using `<multimeasure-rest>`, it is more coherent.

**Comment by clnoel** [comment]
Do we need a "label" that is different from "duration"? It would be optional, of course, defaulting to the duration. Other than that, good tweaks @adrianholovaty. I approve.  

Details/Extra Info:
I'm okay with using measure number, rather than measure location. I think the original proposal used measure location in order to match `<system-layout-change>`. 

I'm thoroughly behind dropping the staff attribute. I was going to mention it myself, then I forgot. Sorry. We can certainly revisit an optional staff attribute here, but I don't see that being needed for v1.

I  am pleased about switching to `<multimeasure-rest>`, as that is actually closer to what I call them in my head (and in my original proposal back in #121.

**Comment by adrianholovaty** [comment]
@cecilios and @clnoel — thanks for the quick reactions! OK, I will go ahead and put a pull request together with this approach.

@clnoel Regarding a `label` attribute, yes, that makes sense (sorry, I meant to write this when you suggested it in the previous comment). I'll add that in the pull request as well.

**Comment by adrianholovaty** [comment]
OK, commit 8e4c1fb added multimeasure rest support to the spec!

Note that issue #286 is still open — regarding a way to encode multimeasure rest style (old-style vs. new-style).
