### ISSUE TITLE
The definitions of "event symbol" and "music notation"

### ISSUE THREAD

**Issue by notator** [w3c/mnx#29]
Issue #26 has shown that I need to define exactly what I mean by "event symbol".
Such a definition may end up in the GMNX documents, so I think its important to get it right and would welcome any suggestions for improving it.

---

### Definition:

In GMNX, an _event symbol_ is a spatial _object_ associated with a temporal _event_.
The _object_ has width, height, x-position and y-position. The x- and y-positions are measured with respect to some known reference point (e.g. a corner of the containing page). 
The _event_ has duration and t-position. The t-position is measured with respect to some known reference instant (e.g. the beginning of a performance).
The units of measurement for width, height , x-position and y-position can, for example, be pixels, millimeters etc.
The units of measurement for duration and t-position can, for example, be seconds, milliseconds etc. 

An _event symbol_ can be represented as an SVG _element_ containing temporal information in a custom namespace.
All _event symbols_ in such an SVG score are at the lowest level in the element tree that can be synchronized during a performance.

---

According to the above definition:
* the following are, for example, _event symbols_:
  * CWMN chord symbols (containing one or more noteheads),
  * CWMN rest symbols,
  * all kinds of Western and Asian tablature symbols,
  * neumes.

* The following are, for example, not _event symbols_:
  * _event symbol components_
    * CWMN noteheads
    * CWMN augmentation dots
  * _containers_
    * page
    * system
    * staff
    * measure
    * voice

**Comment by joeberkovitz** [comment]
While a definition is important, I believe it is already clear from the description given in [Performance Events](https://w3c.github.io/mnx/overview/#performance-events), and winds up yielding the same description as what you have here.

That section says that a performance event connects an `<event>` element in a GMNX `<performance>` to an SVG element. `<event>` elements already have a duration and an onset time (your "t-position") defined as a time in seconds from the beginning of the performance. SVG elements possess an x and y position and width and height, by the very nature of SVG. Thus, in the restricted case of CWMN, we'd wind up with the same classifications of what is and what is not an event symbol as you listed above.

So for this to be an actionable issue, I think you need to state what it is that you want to change relative to the proposal. If the answer is that you want to move temporal information out of a GMNX `<performance>` and into SVG elements, I think that's already covered by #25.

By the way, there is some value in connecting `<note>` elements in a performance to notehead graphics (or their equivalent in non-CWMN notations), although these are technically not "event symbols", so I've added a new issue #30 to reflect this.

**Comment by notator** [comment]
In reply to the objection that only having a few score types is implicitly ethnocentric (#28), I'm working on a new issue that describes how the world's music notations can be classified. This involves providing a definition for "music notation":

---
### Definition:

In GMNX, _music notation_ consists of _event symbols_ contained in nested containers.

---

I should add that _event symbols_ include
* words in ordinary, written text (when associated with a temporal _event_).
That's independent of the direction in which the words are read.

and that the following are not _event symbols_ but _event symbol components_
* lyrics (attached to a CWMN chord symbol)
* ornaments (e.g. CWMN trill characters)
* neumes (added above words that are otherwise written as in ordinary text)

**Comment by notator** [comment]
In his [remarks about the Revised Group Charter](https://www.w3.org/2002/09/wbs/81249/MNCG-2017-1/results), Alexander Plötz said:
> Even Cardew's "Treatise" is fundamentally built from enough "CWMNX" principles that encoding it as such would be by far preferable to encoding it as "GMNX".
 
I don't agree with Alexander about that. In fact I think it would be impossible to encode Cardew's [_Treatise_](https://monoskop.org/images/e/e2/Cardew_Cornelius_Treatise_1967.pdf) in accordance with either CWMNX or GMNX principles (see below).

However, discussing borderline cases is a good way to sharpen our definitions. Alexander seems to be asking for this too, when he continues:
> if anyone will even come up with any criteria for what "GMNX" is supposed to mean beyond "we don't consider it to be Common Western Notation".

The challenge is to define more precisely what we mean by "music notation". In other words, which notations are in scope for GMNX.

My current definition of "music notation" (above) is that it consists of "event symbols" contained in nested containers. So both CWMN and Asian tablatures are "music notation". Ordinary text can also be considered a "music notation", because each word can be considered to be an "event symbol".

In all these cases, a _recognisably similar_ graphic is associated with a _recognisably similar_ event. (e.g. a particular guitar tablature symbol is always associated with the same chord, and a particular word is always associated with a recognisably similar sounding event. And that's true, wherever the symbol occurs in the graphics.) Strictly speaking, the definitions ought to be updated with  "_recognisably similar_".
Event symbols _remind_ a performer what to do at any instant during the performance. Notation conventions (the traditional relations between symbols' graphics and their meanings)  are required for creating high-level musical grammars that are not based on live improvisation. You cant improvise a Brückner Symphony...

So Cardew's Treatise would also be a "music notation", in this strict  sense, if it contained "event symbols" in nested containers. But where are they? The only recognizable, consistently maintained containers I can see are the pages, but their contents are not recognisably similar. There are no repeating constructs at any other level either.
It would be possible to synchronize the score with one or more recordings by assigning particular horizontal regions to particular temporal events, but that would be to ignore the complexity of the graphics. That it appears to have a time axis is not enough for this score to qualify as a "music notation" in the above strict sense.
That does not, of course, mean that this score is rubbish! Its an important representative of the "graphical scores" being written at the time. Essential material for those studying the 20th-century music notation crisis. I personally think of such scores as stimuli for one-off (traditionless) improvisations.

The point is, that the symbols inside such scores resist standardisation, even within a particular score, so they must be out of scope for a standardization effort.

**Comment by joeberkovitz** [comment]
Closing due to lack of any concrete effect on proposals/specifications. GMNX already permits any graphical symbol to be correlated with any temporal event, and events already possess the attributes proposed here.

Please contact chairs directly before posting further on this thread.
