### ISSUE TITLE
Name of <system> element is confusing

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#3]
In MusicXML, the `<system>` element describes the layout characteristics of a musical system (e.g. vertical spacing and the like). The MNX proposal uses this to capture a completely different kind of semantic information.

Perhaps the name of this element should be changed to something clearer, like `<global>` or `<allparts>`.

**Comment by cecilios** [comment]
I fully agree. <allparts> is much more clear. Unless you know very well the specification, the tag <system> creates expectations that have nothing to do with the tag content.

**Comment by joeberkovitz** [comment]
From chair call: this should be clarified and also relates to the question of how we represent part groupings (see #2). In fact, this element could conceivably _be_ the way we define a part group, as mentioned in #33.

**Comment by joeberkovitz** [comment]
This got changed to `<global>`: https://w3c.github.io/mnx/specification/#the-global-element

**Comment by joeberkovitz** [comment]
Chairs think this is resolved -- putting into Active Review to highlight.
