### ISSUE TITLE
Allow GMNX to map performance notes to graphics

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#30]
GMNX `<note>` elements are not events, but there is value in allowing them to be mapped to an SVG graphic that corresponds to that note, if one exists. This permits applications to provide visual feedback or interactivity on individual note graphics, connecting them to individual pitches in the performance. This has particular value for educational use cases.

**Comment by notator** [comment]
In GMNX, noteheads are graphic components of CWMN _event symbols_ (#29). They are SVG <text> elements which could be allowed to have special attributes in an `mnx` namespace.
For example:

```
<text class="quarternotehead" x="770.1572"y="960" mnx:src="csharp.mp3">œ</text>
```

and/or

```
<text class="quarternotehead" x="770.1572" y="960" mnx:frequency"554.37Hz">œ</text>
```

and/or

```
<text class="quarternotehead" x="770.1572" y="960" mnx:midipitch="61">œ</text>
```

I imagine that this capability would be declared in the score type declared in the SVG (as defined in #25).

Note that the notehead's graphic is still independent of its temporal information, so there would be no problem explaining transposition in an an educational project.

**Comment by joeberkovitz** [comment]
@notator You have raised this before, but it is off topic with respect to mapping note-level performance events to graphics (this issue). Your point pertains to including performance information directly in the SVG (covered in #25).

We all understand that it's possible to adopt this approach, and the question deserves debate, but spreading the discussion out like this is making for a confusing process for the CG as a whole. Please don't raise the idea of directly describing performance within the SVG in multiple unrelated issue threads. The chair prefers that this topic be confined to one issue. Build your proposal for embedding performance info into SVG out in #25, and justify why that is better than describing it in a separate structure of its own in terms of what specific benefits it provides to developers and users.

**Comment by notator** [comment]
@joeberkovitz I have never raised this issue before. This idea arose as a direct (and productive) result of the issue you raised here. There is no mention of including note-level performance information in #25. Where better to talk about such progress than here?

I think it would be much less confusing for everyone, if I were allowed to call my version of GMNX by the name SVGMN (at least temporarily). Unfortunately, I have been fobidden to do that. On 28.4.2017 you said, in your "James Ingram's proposals" thread on public-music-notation-contrib:

> In my view, we don't need SVGMN as a separate thing with its own name in order to have the discussion about whether a specialization of SVG is the right way to go.

My latest arguments as to why #25 is the better solution can be found in issue #28. I can't just keep everything in #25.

**Comment by joeberkovitz** [comment]
If the CG adopts the embedded-in-SVG approach in #25, then the rearrangement you are proposing here (note-related information, etc. inside SVG) would come into effect as a natural result of that decision. That would be a far-reaching, cross-cutting decision and we do not want to scatter the discussion among many issues.

I'll ask once again, in my role as co-chair: please restrict the embedding discussion to #25 and make your case there. #25 is the issue that corresponds to what you call SVGMN. Please make your case for the SVG-on-top structure in that location.

**Comment by notator** [comment]
Okay.

**Comment by joeberkovitz** [comment]
A means of mapping performance events to event symbols is supplied in the current spec draft here: https://w3c.github.io/mnx/specification/#the-performance-event-element and is demonstrated in the Fauré example here: https://joeberkovitz.github.io/gmnx-viewer/

**Comment by adrianholovaty** [comment]
(Closing this issue because MNX-Generic is no longer in scope for our community group.)
