### ISSUE TITLE
JSON: Discrepancies between the MNX examples and the Objects' documentation.

### ISSUE THREAD

**Issue by paul-bayleaf** [w3c/mnx#306]
I don't know if it is too early to raise issues with JSON MNX, but there are some discrepancies between the MNX examples and the Objects' documentation.  These are all minor and easily fixed.

Examples https://w3c.github.io/mnx/docs/mnx-reference/examples/
Objects https://w3c.github.io/mnx/docs/mnx-reference/objects/

**1) Event Object property "type" is required but is missing from the following MNX examples:**

Beams (with inner grace notes) 
lines 57, 73, 87, 101, 144

Grace notes (beamed) 
lines 70, 84, 117, 131, 145, 178, 192, 206, 220

Multiple layouts
lines 205, 218, 231, 267, 280, 328, 341, 354, 390, 403, 451, 464, 477, 513, 526, 539, 587, 600, 613, 649, 662

Tempo markings
lines 52, 65, 78, 114, 127, 140

Suggested fix: add missing property "type": "event" to the "event" objects on the lines above.

**2) String property values must be quoted, but the quotes are missing from:**

Jumps (Dal Segno) 
Unquoted string property value on "location" lines 12, 20

Jumps (D.S. al Fine)
Unquoted string property value on "location" lines 12, 17, 24

Suggested fix: add quotes to the above string property values.

**3) Numeric property values must not be quoted, but they are here:**

Key signatures 
Quoted numeric property value "fifths" line 16

Octave shifts (8va) 
Quoted numeric property value "value" line 60

Suggested fix: remove quotes from the above numeric property values

**4) Global Data Object property "measures" is required, but is missing from:**

Orchestral layout 
Empty object "global" line 1

System layouts 
Empty object "global" line 1

Suggested fix add property "measures": [] to the above global objects.

**5) Stave Source Object does not have property"staff" but is used as follows:**

Orchestral layout
"staff" on lines 48, 45

Organ layout
"staff" on lines  lines 27, 36, 48, 91

System layouts
"staff" on lines  lines 70, 79, 156, 165

Suggested fix: in the documentation for Stave Source Object add property "staff".

**6) Stave Source Object does not have property "labelref" but is used as follows:**

System layouts
"labelref" on lines 19, 24, 48, 53, 134, 139

Suggested fix: 

I note that "labelref" is a property of the enclosing Stave Object, should this have been used instead?
Otherwise in the documentation for Stave Source Object add property "labelref".

**7) Note Object does not have property "class" but it is used here:**

Styling via a class (basic)
"class" line 44

Suggested fix: in the documentation for the Note Object add property "class".

**Comment by paul-bayleaf** [comment]
Thanks.   Found another:

**8) Page Object does not have property "measure" and requires property "systems"**

Multimeasure rests
lines 527, 530

Orchestral layout
lines 330, 334

Suggested fix:
Replace
"pages": [ { "measure": 1 } ]

with
"pages": [ { "systems": [ { "measure": 1 } ] } ]

in the above lines (adjusting measure number etc as appropriate)

**Comment by adrianholovaty** [comment]
Thanks again @paul-bayleaf! All of those bugs should now be fixed, with one exception: I didn't fix number 4 on your list, as that document is intentionally partially empty, to focus on the particular aspect of MNX it's trying to demonstrate.

**Comment by mscuthbert** [comment]
Thanks @paul-bayleaf -- this is amazing.  Thank you.  Any other contributions to making MNX even better (with implementations or suggestions) would be so welcomed by the w3c-music notation group!
