### ISSUE TITLE
Distinguish directions that are not scoped to any particular sequence

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#32]
Some directions (e.g. tempo) apply to all events in a measure. Others (e.g. dynamic markings specific to a single polyphonic voice) clearly are scoped to a particular `<sequence>`.

How should these be distinguished in CWMNX? Or should they not be?

**Comment by siennamw** [comment]
It seems to me that being able to scope directions to the particular `<sequence>` to which they apply is important, but it's not obvious to me how this should be done.  Do you have some possibilities in mind that you could describe?

**Comment by joeberkovitz** [comment]
For now, this issue only captures the goal we're trying to address; I don't have a possibility that I like very much yet. And I think the "how" is partly dependent on how we decide to capture directions as per #6.

The main avenue on my mind at the moment is to distinguish `<sequence>` elements relating to the entire measure or to an entire staff within the measure, from others that pertain specifically to polyphonic voices. These non-voice `<sequence>`s would not be able to contain `<event>` children, which suggests that perhaps they shouldn't even have the name element name in the schema.

**Comment by joeberkovitz** [comment]
And... to the extent that we adopt this "non-voice sequence" idea, that sounds like it might overlap with any potential element that we might use to segregate `<direction>`s within voice sequences.

**Comment by joeberkovitz** [comment]
From chairs call today: An explicit `<directions>` container element might make sense here and enforce the inability to include events.

**Comment by joeberkovitz** [comment]
https://w3c.github.io/mnx/specification/#cwmnx-direction-content explains the current proposal for how this works.

**Comment by joeberkovitz** [comment]
The co-chairs reviewed this issue today and believe that [`<directions>`](https://w3c.github.io/mnx/specification/#the-directions-element) as currently speced already distinguishes these cases, so this issue may be closed.
