### ISSUE TITLE
Position: two meanings

### ISSUE THREAD

**Issue by mscuthbert** [w3c/mnx#323]
I'm not sure that it's a good idea to use the term "position" to have two different meanings: one, a vertical offset from middle staff line; the other, a fraction representing a time unit from the beginning of a measure. Seen here in the mid-measure clef change doc:

![image](https://github.com/w3c/mnx/assets/3521479/5c9df9d1-1c6b-43e7-97dc-f046438dd592)

Parsers would probably use a bare int for the former and an object/struct/class for the latter. 

Suggestions to change one of these: for the former include "lineSpace" or "midDistance". For the latter "offset" if not used elsewhere or "timePosition"

**Comment by adrianholovaty** [comment]
Thanks — great point! Let's go with `staffPosition` for clefs and leave `position` for rhythmic position (per our co-chairs chat just now). I'll make the change...
