### ISSUE TITLE
property names convention (camelCase vs kebab-case)

### ISSUE THREAD

**Issue by GeorgeTailor** [w3c/mnx#334]
There is inconsistency in the naming of properties, for example:
- [note docs](https://w3c.github.io/mnx/docs/mnx-reference/objects/note/) have properties names both in camelCase and in kebab-case
- [part docs](https://w3c.github.io/mnx/docs/mnx-reference/objects/part/) have properties named in kebab-case

Now, I know there is no single standard on how to name propeerties in JSON, however, the most popular languages like Python or JS do not have `kebab-case` naming convention. Since the MNX already has some of the properties in camelCase, I suggest to stick to it for every property name consisting of 2 or more words.

**Comment by adrianholovaty** [comment]
Thanks for bringing this up! Our intention is to use camelCase for all the keys. I'll get those specific examples changed.

**Comment by samuelbradshaw** [comment]
Related: https://github.com/w3c/mnx/discussions/304

**Comment by GeorgeTailor** [comment]
ok, here's the list:

- `repeat-end` and `repeat-start` in https://w3c.github.io/mnx/docs/mnx-reference/objects/measure-global/
- `smufl-font` in https://w3c.github.io/mnx/docs/mnx-reference/objects/note/
- `short-name` and `smufl-font` in https://w3c.github.io/mnx/docs/mnx-reference/objects/part/
- `smufl-font` and `stem-direction` in https://w3c.github.io/mnx/docs/mnx-reference/objects/event/
- `grace-type` in https://w3c.github.io/mnx/docs/mnx-reference/objects/grace/
- `make-time`, `steal-previous` and `steal-following` in https://w3c.github.io/mnx/docs/mnx-reference/objects/grace-type/
- `show-number` and `show-value` in https://w3c.github.io/mnx/docs/mnx-reference/objects/tuplet/
- `multimeasure-rests` in https://w3c.github.io/mnx/docs/mnx-reference/objects/score/
- `layout-changes` in https://w3c.github.io/mnx/docs/mnx-reference/objects/system/
- `end-note`, `line-type`, `side-end` and `start-note` in https://w3c.github.io/mnx/docs/mnx-reference/objects/slur/

**Comment by adrianholovaty** [comment]
OK, all JSON keys in the spec now use camel case. No dashes remain.

A few of the possible _values_ still use dashes, but I'll clean those up as a separate line of work.

Thanks again for bringing this to my attention!
