### ISSUE TITLE
Example "Organ layout" missed camelCase update to "layout-changes"

### ISSUE THREAD

**Issue by paul-bayleaf** [w3c/mnx#336]
Example "Organ layout" line 309
"layout-changes": [{"layout": "organ3StaffSplitOber", "location": "1:3/8"}],

Fails to validate with the schema.   After the new camelCase changes this should now be

"layoutChanges": [{"layout": "organ3StaffSplitOber", "location": "1:3/8"}],

**Comment by adrianholovaty** [comment]
Thanks @paul-bayleaf!
