### ISSUE TITLE
neither use Windows newlines nor long lines in repository

### ISSUE THREAD

**Issue by lemzwerg** [w3c/mnx#338]
Please have a look at the current output of gitk.

![image](https://github.com/w3c/mnx/assets/1630245/70cb9a82-0b1a-47f7-abe5-7d4a7e16cd97)

There are two issues.

1. The `document` string uses the Windows line ending format (i.e., `\r\n`) for no good reason.  Please convert the whole repository to only use `\n` for newlines.
2. Having such extremely long lines as for the `document` string makes it *very* hard to quickly compare changes with tools like `gitk`.  Giving that JSON doesn't allow multi-line strings – for me this would have been a reason to not choose JSON at all – I ask to find solutions to avoid that, for example, by putting all those long strings into separate files as plain-text documents, inserting them into the final JSON structure using a post-processor like [jq](https://jqlang.github.io/jq/) by calling `make` or something similar.  [Note that I have zero experience with JSON; maybe `jq` isn't the right tool.]

**Comment by adrianholovaty** [comment]
Thanks for the suggestion. I've changed our docs tool to strip those Windows newline characters in c4e22a31b1.

For the long lines, I've opened issue #340 to keep track of that separately.
