### ISSUE TITLE
Change docgenerator's JSON serialization to use lists of strings

### ISSUE THREAD

**Issue by adrianholovaty** [w3c/mnx#340]
Currently the diffs to the `data.json` file are hard to read, especially for long strings that contain newlines. One way to improve this would be to change the serialization to always store strings as arrays, where each element of the array is a line — effectively just splitting the string by newlines.

Let's give that a shot to see whether it's an improvement (it would otherwise have zero effect on the docs system).

**Comment by mscuthbert** [comment]
Probably would need a way to read in a string for parsing the current specs but write out a list.

**Comment by adrianholovaty** [comment]
Done in 4a2dca56.

**Comment by adrianholovaty** [comment]
@lemzwerg We've already got a system that generates the mnx-schema.json file automatically, and it's much richer than HJSON because it also generates the entirety of the HTML docs and stores a whole bunch of extra metadata. See more info here if you're interested: https://github.com/w3c/mnx/tree/main/docgenerator

**Comment by lemzwerg** [comment]
OK, thanks for the info.
