### ISSUE TITLE
Octave shift camelCase vs kebab-case incostintencies

### ISSUE THREAD

**Issue by GeorgeTailor** [w3c/mnx#344]
https://w3c.github.io/mnx/docs/mnx-reference/objects/octave-shift/

The `type` property should be in camelCase to be consistent with other places in MNX

**Comment by mscuthbert** [comment]
The "value" should also change  -- the example gives another micro-format as a string to parse while the spec says that "octave shift amount" is a number. Neither fits the current direction MNX transposition or placement specifications are going towards.

**Comment by adrianholovaty** [comment]
I've just fixed what I believe is the last case of kebab-case: the `"octave-shift"` string. See aa7e24cd.

With that, I believe this issue can be closed!
