### ISSUE TITLE
Simplify handling of beams

### ISSUE THREAD

**Issue by jsutdolph** [w3c/mnx#35]
I cannot find anything in the draft spec about beams in MNX. Apologies if I have missed something here.
Though MusicXML provides a very detailed specification of beams, almost all of the information can be derived from the note types and so is redundant. The problem with redundant information is that it can be inconsistent, and this we see very often with beam specifications. In fact I believe all or most software which reads MusicXML reconstructs the beams from the note type information.
I believe that the only information actually required is a boolean flag to say if a note is beamed to the following note on the same voice e.g. a "beamToRight" element in the note. This is very simple, and although there is a handful of cases where this information could still be inconsistent, these are easily identified and easily checked.

**Comment by joeberkovitz** [comment]
Correct, beams were not described (along with many other important features of notation).

The problem you point out with explicit vs. implicit rules for beaming is analogous to other areas that have clear rules but also permit deviations, like accidentals. I hope we can find a uniform approach (at least, philosophically) to these various areas.

However I wonder if a "beamToRight" flag may be insufficient to handle some of the alternatives one sees in classical music. There are secondary beams that are sometimes provided by the composer even if they are not strictly necessary. We'd want to handle these to be sure.

@mdgood also pointed out to me that there are issues with the forward/backward directions of the flags that can sometimes hang off of beamed notes.

**Comment by jsutdolph** [comment]
can the special cases be handled as special cases with extra elements leaving the normal cases to be handled in the simplest possible way?

**Comment by joeberkovitz** [comment]
That would certainly be my preference! We are getting ready to move to an MNX specification (as opposed to a proposal) which is the place where these details are going to get resolved.

**Comment by joeberkovitz** [comment]
See https://w3c.github.io/mnx/specification/#elementdef-beamed for the proposal on how this works now.

**Comment by jsutdolph** [comment]
fantastic!

**Comment by jsutdolph** [comment]
This may be closed. The new beam spec is far superior to my idea
