### ISSUE TITLE
Why "The note value base object" supports "2048th", "4096th","duplexMaxima"?

### ISSUE THREAD

**Issue by sunmoondevlab** [w3c/mnx#353]
Why "The note value base object" supports "2048th", "4096th","duplexMaxima"?

See also [Smufl Noteheads (U+E0A0–U+E0FF)](https://w3c.github.io/smufl/latest/tables/noteheads.html)
and [Smufl Flags](https://w3c.github.io/smufl/latest/tables/flags.html).

Not supported "duplexMaxima" noteheads, and "2048th", "4096th" flags.

**Comment by mscuthbert** [comment]
I'm not sure what the question here is.  SMuFL and MNX are related in being by the same working group, but they are not the same product.  There will definitely be things that MNX supports that are not representable in SMuFL and almost certainly (at least in v.1) vice-versa.

**Comment by sunmoondevlab** [comment]
> I'm not sure what the question here is. SMuFL and MNX are related in being by the same working group, but they are not the same product. There will definitely be things that MNX supports that are not representable in SMuFL and almost certainly (at least in v.1) vice-versa.

Thank you for your answer.

Since it is not supported by SmuFL, there is a possibility that it cannot be exported to printable sheet music (mainly in PDF format).

That is why I asked the question.

No point in "duplexMaxima" existing if we don't know how it will be expressed as sheet music.

**Comment by sunmoondevlab** [comment]
The application "Finale" supports 1/4096.
I just noticed that.
So does that mean support for 2048 and 4096 is necessary?
I understand.
I will close this issue.
