### ISSUE TITLE
Lyrics basic and lyrics multi-line examples do not validate against the schema.  Lyrics multi-line example syntax error.

### ISSUE THREAD

**Issue by paul-bayleaf** [w3c/mnx#358]
There are two issues here:

1) Lyrics basic and lyrics multi-line examples do not validate against the schema.  

The schema for the "lyrics" property "lines" will need to use "patternProperties" to allow a user specified property name.  For example.

        "lyrics": {
          "additionalProperties": false,
          "properties": {
            "lines": {
              "additionalProperties": false,
              "patternProperties": {
                "^.*$": {
                  "additionalProperties": false,
                  "properties": {
                    "text": {
                      "$ref": "#/$defs/string"
                    },
                    "type": {
                      "enum": [
                        "start",
                        "middle",
                        "end",
                        "whole"
                      ],
                      "type": "string"
                    }
                  },
                  "required": [
                    "text"
                  ],
                  "type": "object"
                }
              },
              "type": "object"
            }
          },
          "type": "object"
        },

2) Lyrics multi-line example syntax error.

The lyrics multi-line example on line 90 has "hyphen": "start"  this should be "type": "start".

**Comment by adrianholovaty** [comment]
@paul-bayleaf Thanks very much! Both of these are now fixed:

* 88c8141e56 fixed the `"hyphen": "start"`.
* 8866fed2f fixed the JSON Schema to use `"patternProperties"`.

The latter was made possible by an improvement to the docs system ([commit here](https://github.com/w3c-cg/mnxdocgenerator/commit/d2f6d360a0a035d17acbba61d1f1daa2115892d8)).

A related note is: I've just added a way to quickly run the JSON Schema validation on all of the example documents from the command line ([commit here](https://github.com/w3c-cg/mnxdocgenerator/commit/9370e77a6255b5f5ab62539e15ec7254a91e032c)). This is done via `python manage.py validate_json`.
