### ISSUE TITLE
The core of CWMN

### ISSUE THREAD

**Issue by notator** [w3c/mnx#37]
Joe said (in his [response to Alexander's comments on the revised Charter](https://lists.w3.org/Archives/Public/public-music-notation-contrib/2017Aug/0003.html)):

> The co-chairs would like to make it clear that GMNX is about much more than phantom scores. GMNX is a format that can support meaningful rendering of music ranging from the most conservative interpretation of CWMN, to non-Western notational idioms, to one-off experiments in notation from history or in the future.

+10! :-) But I'd like to clarify what he then says (my italics):

> In particular we expect GMNX to be important for a large class of "partly CWMN" scores that incorporate CWMN concepts, but also _break the constraints required to put CWMNX on a solid foundation_.

I think CWMN can be broken down into core constructs and annotations, and that the core constructs _are_  the "solid foundation" of CWMN.
The core constructs in CWMN include systems, staves, clefs and multi-notehead chord (=event) symbols. Constructs like beams, tuplet brackets or augmentation dots were later inventions, and exist simply as annotations (memory aids or aids to reading).

Does that make sense?

**Comment by joeberkovitz** [comment]
@notator Since you have not specified what the practical difference is between a "core construct" and something else, it's not possible to say whether this makes sense.

**Comment by notator** [comment]
The core constructs of CWMN are those that qualify it as a "music notation" in the strict sense defined in issue#29. These constructs are: the containers page, system, and staff (often five lines with clefs), and the chord and rest "event symbols". CWMN chord symbols consist of a combination of notehead(s), accidental(s), stem and flag, whereby none of these is obligatory. At least one notehead and/or a stem must be present. Accidentals don't exist without a corresponding notehead, and flags don't exist without a stem. 

By definition, it is possible to create a ("partly CWMN") "music notation" using just these objects (they are useful for their legibility alone).
Other "partly CWMN" notations can be created by adding further CWMN constructs such as beams, slurs, aumentation dots, tuplet brackets, instrument names, dynamics etc. Since these further objects don't belong to the core, I call them "annotations". Maybe you'd prefer a different word?
Full CWMN consists of the core constructs and all the available "annotations".

The practical difference between core and non-core constructs is that you can't leave a core construct out, and still be left with a "music notation".

Do we agree that the core constructs, as defined above, are the solid foundation of CWMN?

**Comment by joeberkovitz** [comment]
In general, standards groups disallow issues that merely propose a nomenclature or philosophy: issues have to have be couched in terms of concrete alternatives that affect the specification itself.

However, we're not seeing a proposal here on how we would treat a "core" concept differently in CWMNX from an "annotation" concept, other than making "annotations" optional -- but all the elements you mention would already be optional, as is clear in the proposal. And the "core" concepts are already supported in the proposal.

Therefore I'm closing this issue. You can always file an issue later that proposes a concrete alternative to the proposed CWMNX markup.

In the interests of keeping the traffic on the list focused and relevant, please write offline to the co-chairs before posting further on closed issues, including this one.
