### ISSUE TITLE
Clarify mid-measure attribute changes

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#38]
MusicXML 3.x's `<attributes>` element allows (at least in terms of its schema) many kinds of part changes to occur in the middle of a measure. Some of these are solidly idiomatic CWMN changes, for example mid-measure clef changes. Others, it could be argued, do not make sense. For example, mid-measure time signature changes would seem to erode the very concept of "measure". Mid-measure transposition changes feel confusing at the very least (compared to having a different part with its own distinct transposition enter the score at a measure boundary).

Not arguing for a particular outcome here, but this feels like an area that could use clarification in CWMNX.

**Comment by Webern** [comment]
Agreed, mid-measure time-signature changes should be prohibited even if some obscure counter-example can be found in literature (there's always an example).  A class of measure attributes that can only change at the measure boundary is a good concept to have.

**Comment by joeberkovitz** [comment]
I think this is handled now in that mid measure time- and key- signature changes are not allowed in the `standard` profile of CWMNX:  https://w3c.github.io/mnx/specification/#the-time-element and https://w3c.github.io/mnx/specification/#the-key-element
