### ISSUE TITLE
The GMNX viewer

### ISSUE THREAD

**Issue by notator** [w3c/mnx#51]
Thanks very much, Joe for all your recent work for this CG!
I was very excited to see your [GMNX viewer](https://joeberkovitz.github.io/gmnx-viewer/) in action! Real examples are always more exciting than abstract theory! :-)

I was especially taken by the multiple cursors in the Lutoslawski example. Multiple cursors are, of course, perfectly reasonable, but as far as I know, nobody here (including me) has thought about them before.

The best way to clarify the thoughts racing through my mind was to write a small, multi-cursor, demo application (my [oggPngPlayer](http://james-ingram.de/demos/scoreAudioSynchDemo/oggPng.html) ) that duplicates the behaviour in your Lutoslawski example. My code was written quickly from scratch, so its a bit of a hack, but it is at least small and easy to understand. It would have been much better if I had used a proper Cursor class.

Here's a summary of the MNX issues that I think are affected. I am about to write to each one separately, and in more detail, so if anyone has any comments, please add them to my comments there.
- Issue #23: Your GMNX-viewer can be written more simply using standard HTML and SVG. There is no reason to use a `<gmnx>` container tag.

- Issue #29 (currently closed): The algorithm has very little to do with music notation. If the image's internal semantics are ignored, then it can be replaced by any arbitrary image (e.g. a photo of a cat). I think this CG still needs to agree on what "music notation" is, so would like to have Issue #29 re-opened.

- Issue #25: Cursors (in both Joe's and my player) can have any shape, and jump about and move in any direction on the page [1], but I think it would be both simpler and more flexible to define them as single graphic elements that move around the page, not as references to fixed, defined regions in the SVG. That would allow client applications to style them dynamically using CSS, and use the full power of SVG attributes to manipulate them. I'm about to add a "cursors issue" to Issue #25, with an initial, more detailed description of what this means. Can anything similar be done using `<cwmnx>` and `<gmnx>` container tags?

This has been a very productive week! Thanks, Joe, for the provocation!

[1] Composers of graphic scores will love that! Stockhausen (Refrain, Klavierstück XI...), George Crumb and Dennis Báthory-Kitsz spring to mind... :-)

**Comment by joeberkovitz** [comment]
Closing, since this issue does not propose any change to the specification. It only references existing issues, or states an intent to file future issues. All new issues are welcome, but need to meet the group's standards for discussion.
