### ISSUE TITLE
Need to model alternative renditions of scores

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#58]
The `<collection>` element gathers together parts of scores that together make up a whole, such as movements or sections.

MNX however lacks a way of describing that two different scores are alternative renditions of the same music. For example, there is no way to incorporate a CWMNX score and a GMNX score in a container and state that they are different encodings of the same work.

**Comment by joeberkovitz** [comment]
This issue also pertains to alternative _semantic_ representations of the same music (say, individual parts vs. full score).

See [@clnoel's comment on #74](https://github.com/w3c/mnx/issues/74#issuecomment-371243556).

**Comment by mscuthbert** [comment]
I'll post and edit this comment with some examples, mainly from the med/Ren repertory:

A Renaissance (white notation) version of a piece with its retranscription into modern noteshapes (but using the same value):
https://bustena.files.wordpress.com/2015/06/dufay_kyrie1_tenor.png

Ockeghem's famous canon where multiple voices read the same music under different mensuration signs (which affect not only the placement of barlines but also the interpretation of dots, etc.):
original:
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Ockeghem_Prolationum_Kyrie_mensural.svg/2000px-Ockeghem_Prolationum_Kyrie_mensural.svg.png
realization:
https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Ockeghem_Prolationum_Kyrie_incipit.svg/400px-Ockeghem_Prolationum_Kyrie_incipit.svg.png

A canon of the l'homme arme in original notation and realization placed graphically on the same page with connecting graphical elements:
https://youtu.be/IrTtLNfq0x0?t=1m57s

Two notations of the same page being aligned with graphical placement indicating connections among parts, with variants interspersed:
https://www.youtube.com/watch?v=_p9WQlyVPrA

Five or six versions of the same little melody -- aligned with recorded music -- including distinctions between suggested performance and actual performance and an image of the sheet music:
https://www.youtube.com/watch?v=YrOEOuwYy3M

**Comment by mscuthbert** [comment]
Bach's canons and their realizations:
https://www.youtube.com/watch?v=A41CITk85jk

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database.

For anybody visiting this issue page in the future: I believe our concepts of scores and layouts does a decent job of addressing this particular use case. A single MNX document can specify multiple types of graphical displays of the same underlying music. See this example: https://w3c.github.io/mnx/docs/mnx-reference/examples/multiple-layouts/
