### ISSUE TITLE
Only explicitly encoded information in 'global' should be inherited

### ISSUE THREAD

**Issue by cecilios** [w3c/mnx#59]
@joeberkovitz As you requested I open this issue to explain in more detail my comments in #52 about default values inheritance question. But it is nothing really important.

As is logical and desirable, current spec. is dealing with the big picture and low level detail is not currently expected. 

Current spec makes mandatory to include as many `<measure>` elements in `<global>` as measures in the parts. This forces to include many empty `<measure>`elements. At current spec. level the values that will be inherited from these empty measures are not clear and it only points to child elements, such as key signatures, time signatures and tempo indications. The `<measure>` element has/will have attributes. And it should be clarified if the attributes are also inherited or only the content of the `<measure>` element. For instance the value of a `width` attribute. I do not see problems for inheriting also attributes. But this should be clarified when the spec. is more advanced.

Another issue is inheriting not only the explicit content (either children or attributes) but also the implications of what is not included in the content. For instance, in current MusicXML specification a measure without a barline child element implies a simple barline. Current spec. makes barline optional, but says nothing about the implications of not including a barline.

It has been said that in MNX a `<measure>` is just a container without other implications apart from things such as:
- Transferring one application's notion of "measure" to another application, as not every barline corresponds to a measure boundary.
- Facilitating DOM operations.
- Practical aspects such as facilitating source code inspection and using source code folding.

First of all let me say that I recognize these benefits and consider the measure container useful for that, and I will not argue against using the `<measure>` element, but just for that: as a container, an additional `<div>` tag without major implications. Or at least, without implications that would make more difficult to create applications not centered in measures. Making `<measure>` elements mandatory in `<global>` and not mentioning barline implications could be signal that the idea of using `<measure>` as container and trying to remove as much as possible other negative implications for other applications is not yet totally assumed. Probably, current spec. has the implicit assumption that all those empty `<measure>` measures in `<global>` provide simple barlines for the parts.

At this stage of the draft it would be better not to start assuming default values implications until the draft is more elaborated and it is a clear advantage to provide default content when nothing is explicitly encoded. Therefore, I think it is cleaner to make  the `<barline>` element mandatory when there is a barline, instead of starting to assume things. An explicit barline is better for a DOM model. Anyway, I'm not against an implicit 'simple barline' implied by the  `<measure>` container but would like to see that this is a concious decision, based on tangible gains, and not just heritage from MusicXML.

~~Another different issue: it has to be decided if global information can be overridden by the parts. My first impression is that it is beneficial and doesn't cause any harm.~~ [edited: in the light of my comments in #55 overrides must not be allowed, as `<global>` represents global constrains]

**Comment by adrianholovaty** [comment]
Marking this as closed, for the sake of cleaning up our issue database. This is very outdated — it deals with the older XML version of MNX.
