### ISSUE TITLE
event symbols

### ISSUE THREAD

**Issue by notator** [w3c/mnx#60]
The definition of _notated event_
https://w3c.github.io/mnx/specification/#notated-event
applies only to CWMN, but CWMN is not the only notation to contain notated events.
I think the definition could and should be made more general, so that it applies to _all_ music notations. The generalisation would be something like the _event symbol_ definition in #29.

**Comment by joeberkovitz** [comment]
Closing since the definition of _event symbol_ is framed as specific to MNX-Common alone. If we need a more general definition for some future specification, we can create one.
