### ISSUE TITLE
Use container element for style decls

### ISSUE THREAD

**Issue by mscuthbert** [w3c/mnx#83]
I can't find an issue devoted to discussion of the style, class, style-class, etc. so I'm hoping it's welcome to start one.

I see in the Proposal Overview (https://w3c.github.io/mnx/overview/#css-and-style-properties) that CSS stylesheets were the recommended definition, but in the latest Draft Specification (https://w3c.github.io/mnx/specification/#elementdef-style-selector) these have been replaced with style-class and style-selector tags, and I'm wondering about the rationale for the change and other related issues.

My feeling is that while CSS stylesheets add a second parser type, and thus add to the complexity of MNX agents, they're something that there is a large, open-source ecosystem that is able to parse and deal with them and many of the difficult corner cases regarding conflicting styles, computed values, etc., have already been solved, while style classes can be much more difficult.  Doesn't it make sense to be able to do something like `part#ossiaStaff note { notehead-size: 8st }` rather than need to define an `eighttenths` class and apply that to every note in the part?

**Comment by joeberkovitz** [comment]
@mscuthbert Just to fill in the rationale (without prejudice!), the change occurred for two reasons:

-  a number of CG members voiced discomfort with having to support a general CSS parser and selector-engine

- the chairs got guidance from folks involved with the W3C CSS WG that we should not duplicate the mechanism outright as it had evolved from a mix of very different needs arising from the HTML ecosystem including legacy considerations.

So: the current draft spec pares this back to simply classes and selectors with a single simple "element name match" rule. This is functionally equivalent to CSS stylesheets but uses XML syntax, and has only two kinds of rules: classes and element-names. We have left room to add more kinds of rules to `<style-selector>' if there is sufficient consensus in the CG.

By the way, your ossia staff could be handled with a `ossiaStaff` class name on the ossia's `<staff-details>` element, so I don't think one really needs to apply it to every note in the part.  I think classes and element name matches are the powerful CSS tools, not so much ID names (`#ossiaStaff`) which give one little advantage over in-line styling.

**Comment by mscuthbert** [comment]
Thanks for the explanation

Perhaps notehead size is something that can be applied to every note via a `<staff-details>` element, but I imagine that there are a number of other cases, such as ensuring that all sharps in one part default to a particular smufl character that would be better handled by a selector than a class on each accidental tag.  But I haven't needed to build notation systems with the type of responsiveness as others in the CG, so it's possible I prioritize flexibility over speed/simplicity more than others.

**Comment by joeberkovitz** [comment]
I agree that the issue is real. I see the level of "style firepower" as something we should come back to down the line when we have more examples of what members want to do. The CSS WG built up their current specs over 4 iterations!

**Comment by joeberkovitz** [comment]
Chairs: we opened this today because we want to finalize the form in which MNX-Common style properties are encoded early on.

**Comment by cecilios** [comment]
I'm glad with the change, so that no necessity to increase the complexity of consumer applications by having to include a CSS parser and the algorithms for style selection. Great!
 
I would suggest wrapping all 'style-selector' and 'style-class' elements into a 'styles' container element:

```
  <head>
    <title>
	...
    <styles>
	 <style-selector rule= ... />
	 <style-selector rule= ... />
	 <style-selector rule= ... />
    	 <style-class name= ... />
    	 <style-class name= ... />
    </styles>
  </head>
```

This wrapper doesn't cause any problem, can simplify traversing the document, and helps to structure the MNX code and to facilitate inspecting MNX files in xml editors with hierarchical code folding.

**Comment by joeberkovitz** [comment]
Retitled to reflect the remaining content in this issue.  PR ensuing forthwith.
