### ISSUE TITLE
Distinguish direction elements with duration from those that don't

### ISSUE THREAD

**Issue by joeberkovitz** [w3c/mnx#9]
The `<direction>` element in CWMNX (as in MusicXML) covers a wide array of notations, including at least two broad categories:

- "point-like" notations that lack a concept of duration (e.g. words, dynamics, articulations)
- "span-like" notations that span a duration within some part (e.g. lines, slurs, hairpins)

Should these two be assigned different element names to reflect this fundamental distinction?

**Comment by joeberkovitz** [comment]
In the current spec draft these are both considered directions, but they are placed into distinct families. So this issue seems resolved.

**Comment by mdgood** [comment]
As the chairs believe this issue is resolved, we plan to be closing this issue.
