### ISSUE TITLE
clef changes within beamed groups

### ISSUE THREAD

**Issue by jsutdolph** [w3c/mnx#96]
![screen shot 2018-04-09 at 11 42 08](https://user-images.githubusercontent.com/13803204/38493733-13c37bb0-3beb-11e8-9d90-893d569f72ab.png)
I have read the spec on beamed groups and I don't see how clef changes within groups are supported. Probably just a misunderstanding

**Comment by clnoel** [comment]
The `<clef>` element, like all directions, has a location attribute. In the above work,  the starting clef is in the global, with location 0. The next clef would have location 1/8. What's not clear in the spec is whether the second clef should be in the global or be part of the sequence.

**Comment by clnoel** [comment]
@joeberkovitz A sequence specific clef might actually make sense, like in this example that was pulled from the MusicXML conversation on almost this same topic from two years ago:

![image](https://user-images.githubusercontent.com/6453511/38585009-ec7fd1ea-3cdd-11e8-9fa2-21ca43c2c7e1.png)

Not exactly the current topic, but definitely related!

**Comment by joeberkovitz** [comment]
Oh yeah, forgot about that one! Although it's probably outside the well-behaved boundary we'd still need to decide if a sequence-specific clef is the way that things like the above are encoded.

**Comment by adrianholovaty** [comment]
Closing this in favor of #313.
